Repository jfrog/jfrog-cli-core, pull requests merged in 2022-12, with the labels that each got.

#631 Disable default Docker scan suggestion
  artifactory/utils/container/containermanager.go
Labels: improvement

#633 Transfer - UI fixes for Windows
  artifactory/commands/transferfiles/longpropertycheck.go
  artifactory/commands/transferfiles/status.go
  artifactory/commands/transferfiles/transferfileprogress.go
  jfrog-cli-core/go.mod
  utils/progressbar/progressbarmng.go
Labels: bug

#636 Delete jfrog-cli-core dir
  jfrog-cli-core/go.mod
Labels: ignore for release

#640 Transfer files - fix parsing error in progress bar
  artifactory/commands/transferfiles/fulltransfer.go
Labels: bug

#586 Upload - Take into account the repository name with exclude pattern and include directory flags
  artifactory/commands/buildinfo/adddependencies.go
  go.mod
  go.sum
  xray/commands/scan/scan.go
Labels: ignore for release

#635 Transfer - add repository snapshot manager
  artifactory/commands/transferfiles/fulltransfer.go
  artifactory/commands/transferfiles/manager.go
  artifactory/commands/transferfiles/state/runstatus.go
  artifactory/commands/transferfiles/state/state.go
  artifactory/commands/transferfiles/state/state_test.go
  artifactory/commands/transferfiles/state/statemanager.go
  artifactory/commands/transferfiles/state/testutils.go
  artifactory/commands/transferfiles/state/timeestimation_test.go
  artifactory/commands/transferfiles/state/transfersnapshot.go
  artifactory/commands/transferfiles/state/utils.go
  artifactory/commands/transferfiles/status.go
  artifactory/commands/transferfiles/status_test.go
  artifactory/commands/transferfiles/transfer.go
  artifactory/commands/transferfiles/utils.go
  utils/coreutils/coreconsts.go
  utils/reposnapshot/node.go
  utils/reposnapshot/node_test.go
  utils/reposnapshot/snapshotmanager.go
  utils/reposnapshot/snapshotmanager_test.go
  utils/reposnapshot/testdata/dummy-repo-local
Labels: improvement

#644 Fix docker scan by repo-path
  artifactory/commands/utils/dockercmdutils.go
  xray/commands/scan/dockerscan.go
Labels: bug

#626 Transfer config - Optionally check remote repositories URLs
  artifactory/commands/transferconfig/transferconfig.go
  artifactory/commands/transferconfig/transferconfig_test.go
  artifactory/commands/transferconfig/utils.go
  artifactory/commands/transferfiles/longpropertycheck.go
  artifactory/commands/utils/remoteurlchecker.go
  artifactory/commands/utils/transferconfigutils.go
  artifactory/commands/utils/transferconfigutils_test.go
Labels: improvement

#642 Fix poetry install issue and test
  .github/workflows/test.yml
  artifactory/commands/python/poetry.go
  artifactory/commands/python/poetry_test.go
  go.mod
  go.sum
  xray/audit/python/python_test.go
  xray/commands/testdata/poetry-project/poetry.lock
Labels: bug

#648 Transfer config code improvements
  artifactory/commands/transferconfig/transferconfig.go
  utils/coreutils/utils.go
Labels: ignore for release

#647 Add .frogbot/frogbot-config.yml
  .frogbot/frogbot-config.yml
Labels: ignore for release
