Repository jfrog/jfrog-cli-core, pull requests merged in 2022-09, with the labels that each got.

#533 Fix Audit wrong Nuget tree calculation
  artifactory/commands/transferfiles/transfer.go
  go.mod
  go.sum
  xray/audit/commonutils.go
  xray/audit/nuget/nuget.go
Labels: bug

#530 Transfer config - avoid encryption if not needed
  artifactory/commands/transferconfig/transferconfig.go
  artifactory/commands/transferconfig/utils.go
  go.mod
  go.sum
Labels: bug

#536 Support MAVEN_OPTS with multiple spaces between flags
  utils/mvn/utils.go
Labels: bug

#535 Transfer files - better handling graceful stop
  artifactory/commands/transferfiles/filesdiff.go
  artifactory/commands/transferfiles/fulltransfer.go
  artifactory/commands/transferfiles/manager.go
  artifactory/commands/transferfiles/phase.go
  artifactory/commands/transferfiles/propertiesdiff.go
  artifactory/commands/transferfiles/transfer.go
  artifactory/commands/transferfiles/transfer_test.go
  artifactory/commands/transferfiles/utils.go
  artifactory/commands/transferfiles/utils_test.go
  artifactory/utils/storageinfo.go
  artifactory/utils/storageinfo_test.go
  artifactory/utils/utils.go
Labels: improvement

#538 Transfer - fix number of reposiories in progress
  artifactory/commands/gradle/gradle.go
  artifactory/commands/transferfiles/transfer.go
  artifactory/commands/transferfiles/transfer_test.go
Labels: bug

#539 Transfer - skip handling errors if not needed
  artifactory/commands/transferfiles/filesdiff.go
Labels: improvement

#540 Improvement - fix technology naming
  general/cisetup/cisetup.go
  general/cisetup/jenkinsfiledslgenerator.go
  general/project/repoutils.go
  utils/coreutils/techutils.go
  xray/audit/commonutils.go
  xray/audit/python/python.go
  xray/commands/audit/generic/auditmanager.go
  xray/formats/simplejsonapi.go
  xray/utils/resultstable.go
  xray/utils/resultwriter.go
Labels: improvement

#543 Bug Fix - skip empty CVE score on Sarif report CVE calculation
  utils/coreutils/techutils.go
  xray/utils/resultwriter.go
  xray/utils/resultwriter_test.go
Labels: bug

#544 Transfer - Avoid uploading empty build-info dirs
  artifactory/commands/transferfiles/api.go
  artifactory/commands/transferfiles/fulltransfer.go
  artifactory/commands/transferfiles/transfer_test.go
  artifactory/commands/transferfiles/utils.go
Labels: bug

#542 Transfer config - remove all federated members
  artifactory/commands/testdata/config_xmls_federated_repos/expected/artifactory.config-0.xml
  artifactory/commands/testdata/config_xmls_federated_repos/expected/artifactory.config-1.xml
  artifactory/commands/testdata/config_xmls_federated_repos/expected/artifactory.config-2.xml
  artifactory/commands/testdata/config_xmls_federated_repos/expected/artifactory.config-3.xml
  artifactory/commands/transferconfig/configxmlutils/federatedrepos.go
  artifactory/commands/transferconfig/configxmlutils/fereratedrepos_test.go
  artifactory/commands/transferconfig/transferconfig.go
Labels: improvement

#524 Warn when configuring unsafe HTTP connections
  common/commands/config.go
  common/commands/config_test.go
Labels: improvement

#547 Improve bugs reporting view to Github's new Issue Form UI
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: ignore for release

#545 Fix Dotnet configfile usage
  artifactory/commands/dotnet/dotnetcommand.go
  artifactory/commands/dotnet/dotnetcommand_test.go
  artifactory/commands/dotnet/dotnetcorecli.go
  artifactory/commands/dotnet/nuget.go
  go.mod
  go.sum
Labels: bug, breaking change

#548 Transfer files - remaining time estimation
  artifactory/commands/transferfiles/api.go
  artifactory/commands/transferfiles/filesdiff.go
  artifactory/commands/transferfiles/fulltransfer.go
  artifactory/commands/transferfiles/manager.go
  artifactory/commands/transferfiles/phase.go
  artifactory/commands/transferfiles/propertiesdiff.go
  artifactory/commands/transferfiles/state.go
  artifactory/commands/transferfiles/timeestimation.go
  artifactory/commands/transferfiles/transfer.go
  artifactory/commands/transferfiles/transfer_test.go
  artifactory/commands/transferfiles/transferfileprogress.go
  artifactory/commands/transferfiles/utils.go
  artifactory/utils/storageinfo.go
  utils/progressbar/progressbarmng.go
Labels: feature request

#466 Add Poetry support
  .github/workflows/test.yml
  go.mod
  go.sum
  utils/coreutils/techutils.go
  xray/audit/python/python.go
  xray/audit/python/python_test.go
  xray/commands/audit/generic/auditmanager.go
  xray/commands/testdata/poetry-project/my_poetry_project/__init__.py
  xray/commands/testdata/poetry-project/poetry.lock
  xray/commands/testdata/poetry-project/pyproject.toml
  xray/commands/testdata/poetry-project/tests/__init__.py
  xray/commands/testdata/poetry-project/tests/test_my_poetry_project.py
Labels: new feature

#550 Transfer - producer consumers fixes
  artifactory/commands/transferfiles/delayedartifactshandler.go
  artifactory/commands/transferfiles/filesdiff.go
  artifactory/commands/transferfiles/fulltransfer.go
  artifactory/commands/transferfiles/manager.go
  artifactory/commands/transferfiles/utils.go
Labels: bug

#554 Transfer - Add time estimation tests and temporary disable
  artifactory/commands/transferfiles/manager.go
  artifactory/commands/transferfiles/state_test.go
  artifactory/commands/transferfiles/timeestimation.go
  artifactory/commands/transferfiles/timeestimation_test.go
  artifactory/commands/transferfiles/transfer.go
  artifactory/commands/transferfiles/transferfileprogress.go
  artifactory/utils/storageinfo_test.go
Labels: ignore for release

#552 Transfer - Support HTTP proxy and check connectivity
  artifactory/commands/transferfiles/api.go
  artifactory/commands/transferfiles/fulltransfer.go
  artifactory/commands/transferfiles/phase.go
  artifactory/commands/transferfiles/propertiesdiff.go
  artifactory/commands/transferfiles/srcpluginservice.go
  artifactory/commands/transferfiles/transfer.go
  artifactory/commands/transferfiles/transfer_test.go
  artifactory/commands/transferfiles/utils.go
Labels: improvement

#551 Transfer files - moving errors handling to new phase
  artifactory/commands/transferfiles/filesdiff.go
  artifactory/commands/transferfiles/fileserror.go
  artifactory/commands/transferfiles/fulltransfer.go
  artifactory/commands/transferfiles/phase.go
  artifactory/commands/transferfiles/propertiesdiff.go
  artifactory/commands/transferfiles/srcpluginservice.go
  artifactory/commands/transferfiles/state.go
  artifactory/commands/transferfiles/transferfileprogress.go
  artifactory/commands/transferfiles/utils.go
Labels: new feature

#546 Transfer Files - Add report usage SH size and service id
  artifactory/commands/transferfiles/transfer.go
  artifactory/utils/storageinfo.go
  go.mod
  go.sum
Labels: new feature

#556 Take pip3 instead of pip on pip audit command
  xray/audit/python/python.go
  xray/commands/audit/generic/auditmanager.go
Labels: improvement

#557 Bug fix - GetReposTotalSize was missing reset between polling
  artifactory/utils/storageinfo.go
  artifactory/utils/storageinfo_test.go
Labels: bug

#558 Transfer - Estimated remaining time improvements
  artifactory/commands/transferfiles/timeestimation.go
  artifactory/commands/transferfiles/timeestimation_test.go
Labels: ignore for release

#559 Python - Return missed build info error
  artifactory/commands/python/python.go
Labels: bug

#560 Transfer files - fix max snapshots on fede repos
  artifactory/commands/transferfiles/utils.go
  artifactory/commands/transferfiles/utils_test.go
Labels: bug

#561 Fix Python command missing catch error
  artifactory/commands/python/python.go
Labels: bug

#562 Support Npm Auth with Identity/Reference Token
  artifactory/commands/utils/npmcmdutils.go
Labels: improvement

#563 Transfer - Adding failures counter to progress bar
  artifactory/commands/transferfiles/errorshandler.go
  artifactory/commands/transferfiles/errorshandler_test.go
  artifactory/commands/transferfiles/fileserror.go
  artifactory/commands/transferfiles/transfer.go
  artifactory/commands/transferfiles/transferfileprogress.go
  artifactory/commands/transferfiles/utils.go
  utils/progressbar/progressbarmng.go
Labels: new feature

#565 Transfer files - Better handling context canceled
  artifactory/commands/transferfiles/utils.go
Labels: bug

#567 Transfer - Simplify handleFilesOfCompletedChunk
  artifactory/commands/transferfiles/utils.go
Labels: ignore for release

#549 Add Poetry commands
  artifactory/commands/buildinfo/publish.go
  artifactory/commands/python/pip.go
  artifactory/commands/python/pipenv.go
  artifactory/commands/python/poetry.go
  artifactory/commands/python/python.go
  artifactory/commands/utils/configfile.go
  artifactory/utils/projectconfig.go
  go.mod
  go.sum
  xray/audit/python/python.go
Labels: new feature
