Repository jfrog/jfrog-cli-core, pull requests merged in 2022-11, with the labels that each got.

#605 New distribution mock server
  artifactory/commands/transferconfig/transferconfig_test.go
  artifactory/commands/transferfiles/transfer_test.go
  artifactory/utils/storageinfo.go
  common/tests/utils.go
  go.mod
  go.sum
Labels: ignore for release

#601 Transfer - Time estimation enabling and improvements
  artifactory/commands/transferfiles/api/types.go
  artifactory/commands/transferfiles/delayedartifactshandler.go
  artifactory/commands/transferfiles/delayedartifactshandler_test.go
  artifactory/commands/transferfiles/errorshandler.go
  artifactory/commands/transferfiles/errorshandler_test.go
  artifactory/commands/transferfiles/filesdiff.go
  artifactory/commands/transferfiles/fileserror.go
  artifactory/commands/transferfiles/fulltransfer.go
  artifactory/commands/transferfiles/manager.go
  artifactory/commands/transferfiles/phase.go
  artifactory/commands/transferfiles/srcpluginservice.go
  artifactory/commands/transferfiles/state/runstatus.go
  artifactory/commands/transferfiles/state/runstatus_test.go
  artifactory/commands/transferfiles/state/state.go
  artifactory/commands/transferfiles/state/state_test.go
  artifactory/commands/transferfiles/state/statemanager.go
  artifactory/commands/transferfiles/state/statemanager_test.go
  artifactory/commands/transferfiles/state/testutils.go
  artifactory/commands/transferfiles/state/timeestimation.go
  artifactory/commands/transferfiles/state/timeestimation_test.go
  artifactory/commands/transferfiles/state/utils.go
  artifactory/commands/transferfiles/state/utils_test.go
  artifactory/commands/transferfiles/status.go
  artifactory/commands/transferfiles/status_test.go
  artifactory/commands/transferfiles/summary_test.go
  artifactory/commands/transferfiles/timeestimation.go
  artifactory/commands/transferfiles/timeestimation_test.go
  artifactory/commands/transferfiles/transfer.go
  artifactory/commands/transferfiles/transfer_test.go
  artifactory/commands/transferfiles/transferfileprogress.go
  artifactory/commands/transferfiles/utils.go
  artifactory/utils/storageinfo.go
  artifactory/utils/storageinfo_test.go
  utils/lock/lock.go
Labels: improvement

#610 Transfer - Fix docker file transfer in phase 2
  artifactory/commands/transferfiles/filesdiff.go
  artifactory/commands/transferfiles/phase.go
  artifactory/commands/transferfiles/transfer.go
Labels: bug

#611 [Unreleased bug] Transfer - Fix "status" view layout
  artifactory/commands/transferfiles/status.go
Labels: ignore for release

#613 Fix transfer show status tests
  artifactory/commands/transferfiles/status_test.go
Labels: ignore for release

#612 Transfer - Illegal AQL query may be sent in Phase 2
  artifactory/commands/transferfiles/filesdiff.go
Labels: bug

#603 Upgrade to GO 1.19
  .github/workflows/analysis.yml
  .github/workflows/frogbot-scan-and-fix.yml
  .github/workflows/frogbot-scan-pr.yml
  .github/workflows/test.yml
  artifactory/commands/dotnet/dotnetcommand.go
  artifactory/commands/golang/publish.go
  artifactory/commands/npm/common.go
  artifactory/commands/npm/publish.go
  artifactory/commands/permissiontarget/template.go
  artifactory/commands/python/dependencies/cache.go
  artifactory/commands/python/dependencies/dependencies.go
  artifactory/commands/replication/template.go
  artifactory/commands/repository/template.go
  artifactory/commands/transferfiles/errorshandler_test.go
  artifactory/commands/transferfiles/utils.go
  artifactory/commands/utils/configfile.go
  artifactory/commands/utils/result.go
  artifactory/commands/utils/yarnutils.go
  artifactory/utils/buildutils.go
  artifactory/utils/container/buildinfo.go
  artifactory/utils/npm/config-list.go
  artifactory/utils/npm/pack_test.go
  artifactory/utils/transfersettings.go
  artifactory/utils/utils.go
  common/commands/config.go
  general/project/projectinit.go
  go.mod
  go.sum
  utils/config/config.go
  utils/config/config_test.go
  utils/config/tests/utils.go
  utils/plugins/utils.go
  utils/plugins/utils_test.go
  xray/audit/npm/npm_test.go
  xray/audit/nuget/nuget_test.go
  xray/commands/offlineupdate/offlineupdate.go
  xray/commands/offlineupdate/offlineupdate_test.go
  xray/utils/downloadindexer.go
Labels: improvement

#589 Upgrade GO to 1.19
  artifactory/commands/dotnet/dotnetcommand.go
  artifactory/commands/gradle/gradle.go
  artifactory/commands/mvn/mvn.go
  artifactory/commands/npm/installorci.go
  artifactory/commands/npm/installorci_test.go
  artifactory/commands/npm/publish.go
  artifactory/commands/permissiontarget/template.go
  artifactory/commands/replication/template.go
  artifactory/commands/repository/template.go
  artifactory/commands/utils/configfile.go
  artifactory/commands/utils/npmcmdutils.go
  artifactory/commands/utils/result.go
  artifactory/utils/buildinfoproperties.go
  artifactory/utils/buildutils.go
  artifactory/utils/container/buildinfo.go
  artifactory/utils/dotnet/dependencies/assetsjson.go
  artifactory/utils/dotnet/dependencies/packagesconfig.go
  artifactory/utils/dotnet/solution/solution.go
  artifactory/utils/golang/project/project.go
  artifactory/utils/npm/config-list.go
  artifactory/utils/npm/list.go
  artifactory/utils/npm/pack_test.go
  artifactory/utils/pip/dependencies/cache.go
  artifactory/utils/pip/dependencies/dependencies.go
  artifactory/utils/pip/setuppy.go
  artifactory/utils/utils.go
  bintray/helpers/streammanager.go
  common/commands/config.go
  go.mod
  go.sum
  utils/config/config.go
  utils/config/config_test.go
  utils/config/tests/utils.go
  utils/npm/packageInfo.go
  xray/commands/offlineupdate/offlineupdate.go
  xray/utils/downloadindexer.go
Labels: improvement

#614 Transfer - wrong storage and files count in status
  artifactory/commands/transferfiles/state/statemanager.go
Labels: bug

#615 Transfer - Shorten phase 2 docker AQL
  artifactory/commands/transferfiles/filesdiff.go
Labels: ignore for release

#577 Transfer - Double value progress bar
  .github/workflows/frogbot-scan-pr.yml
  artifactory/commands/transferfiles/api/types.go
  artifactory/commands/transferfiles/filesdiff.go
  artifactory/commands/transferfiles/fulltransfer.go
  artifactory/commands/transferfiles/manager.go
  artifactory/commands/transferfiles/state/runstatus.go
  artifactory/commands/transferfiles/state/state.go
  artifactory/commands/transferfiles/state/statemanager.go
  artifactory/commands/transferfiles/state/timeestimation.go
  artifactory/commands/transferfiles/state/timeestimation_test.go
  artifactory/commands/transferfiles/status.go
  artifactory/commands/transferfiles/status_test.go
  artifactory/commands/transferfiles/transfer.go
  artifactory/commands/transferfiles/transferfileprogress.go
  artifactory/utils/storageinfo.go
  artifactory/utils/storageinfo_test.go
  utils/progressbar/progressbarmng.go
Labels: improvement

#617 Improve interactive 'config add' UI
  common/commands/config.go
  utils/ioutils/ioutils.go
Labels: improvement

#609 Fix pip dependencies script for python 3.11
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/test.yml
  go.mod
  go.sum
  xray/audit/python/python.go
  xray/audit/python/python_test.go
Labels: improvement

#616 Ask for username when the given access token is a reference token
  artifactory/commands/dotnet/dotnetcommand.go
  artifactory/commands/golang/go.go
  artifactory/commands/golang/go_test.go
  artifactory/commands/python/poetry.go
  artifactory/commands/python/python.go
  artifactory/utils/buildinfoproperties.go
  artifactory/utils/container/containermanager.go
  common/commands/config.go
  common/commands/config_test.go
  general/cisetup/pipelinesconfig.go
  go.mod
  go.sum
Labels: improvement

#598 Verify gradle wrapper on gradle audit
  xray/audit/java/gradle.go
  xray/audit/java/gradle_test.go
Labels: improvement

#618 Transfer - Added emojis to progress bar + fix bug
  artifactory/commands/transferfiles/fulltransfer.go
  artifactory/commands/transferfiles/manager.go
  artifactory/commands/transferfiles/status.go
  artifactory/commands/transferfiles/transferfileprogress.go
  utils/progressbar/progressbarmng.go
Labels: ignore for release

#619 Transfer - fix NPD in CI mode
  artifactory/commands/transferfiles/filesdiff.go
  artifactory/commands/transferfiles/manager.go
  artifactory/commands/transferfiles/transferfileprogress.go
Labels: ignore for release

#620 Transfer - adding pre-check flag option to run checks on Artifactory server
  artifactory/commands/transferfiles/longpropertycheck.go
  artifactory/commands/transferfiles/longpropertycheck_test.go
  artifactory/commands/transferfiles/transfer.go
  artifactory/commands/utils/checkrunner.go
  artifactory/commands/utils/checkrunner_test.go
  utils/progressbar/progressbarmng.go
Labels: new feature

#624 Fix go vet for progress bar
  artifactory/commands/transferfiles/transferfileprogress.go
  utils/progressbar/progressbarmng.go
Labels: ignore for release

#622 Fix storage info overflow
  artifactory/utils/storageinfo.go
  artifactory/utils/storageinfo_test.go
  utils/progressbar/progressbarmng.go
Labels: bug

#602 Add install data transfer plugin command
  artifactory/commands/transferinstall/datatransferinstall.go
  artifactory/commands/transferinstall/datatransferinstall_test.go
Labels: new feature

#627 Add storage and files counters to Phase2 and phase3 progressbars
  artifactory/commands/transferfiles/api/types.go
  artifactory/commands/transferfiles/delayedartifactshandler.go
  artifactory/commands/transferfiles/delayedartifactshandler_test.go
  artifactory/commands/transferfiles/filesdiff.go
  artifactory/commands/transferfiles/fileserror.go
  artifactory/commands/transferfiles/fulltransfer.go
  artifactory/commands/transferfiles/manager.go
  artifactory/commands/transferfiles/phase.go
  artifactory/commands/transferfiles/state/state.go
  artifactory/commands/transferfiles/state/statemanager.go
  artifactory/commands/transferfiles/state/statemanager_test.go
  artifactory/commands/transferfiles/state/timeestimation.go
  artifactory/commands/transferfiles/state/timeestimation_test.go
  artifactory/commands/transferfiles/status.go
  artifactory/commands/transferfiles/status_test.go
  artifactory/commands/transferfiles/transferfileprogress.go
  artifactory/commands/transferfiles/utils.go
  utils/progressbar/progressbarmng.go
Labels: improvement

#625 Transfer - Restructure to repository separation
  artifactory/commands/transferfiles/delayedartifactshandler.go
  artifactory/commands/transferfiles/delayedartifactshandler_test.go
  artifactory/commands/transferfiles/errorshandler.go
  artifactory/commands/transferfiles/errorshandler_test.go
  artifactory/commands/transferfiles/filesdiff.go
  artifactory/commands/transferfiles/fileserror.go
  artifactory/commands/transferfiles/fulltransfer.go
  artifactory/commands/transferfiles/manager.go
  artifactory/commands/transferfiles/state/runstatus.go
  artifactory/commands/transferfiles/state/runstatus_test.go
  artifactory/commands/transferfiles/state/state.go
  artifactory/commands/transferfiles/state/state_test.go
  artifactory/commands/transferfiles/state/statemanager.go
  artifactory/commands/transferfiles/state/statemanager_test.go
  artifactory/commands/transferfiles/state/testutils.go
  artifactory/commands/transferfiles/state/timeestimation_test.go
  artifactory/commands/transferfiles/state/utils.go
  artifactory/commands/transferfiles/status.go
  artifactory/commands/transferfiles/status_test.go
  artifactory/commands/transferfiles/transfer.go
  artifactory/commands/transferfiles/transferfileprogress.go
  artifactory/commands/transferfiles/utils.go
  artifactory/commands/transferfiles/utils_test.go
  utils/coreutils/coreconsts.go
  utils/coreutils/utils.go
Labels: breaking change, improvement

#632 Fix TestSplitComponentId
  artifactory/utils/storageinfo_test.go
Labels: ignore for release
