Repository jfrog/jfrog-cli-core, pull requests merged in 2022-06, with the labels that each got.

#406 Duplicate build-info's artifacts are counted by their paths instead of their names
  go.mod
  go.sum
Labels: bug

#404 Remove repository name from artifacts' path field in the build-info JSON
  go.mod
  go.sum
Labels: breaking change

#405 Move Dotnet to build-info-go
  artifactory/commands/dotnet/dotnetcommand.go
  artifactory/commands/dotnet/dotnetcommand_test.go
  artifactory/commands/dotnet/dotnetcorecli.go
  artifactory/commands/dotnet/nuget.go
  artifactory/commands/dotnet/testdata/slnDir/packages.config
  artifactory/commands/dotnet/testdata/slnDir/proj.csproj
  artifactory/commands/dotnet/testdata/slnDir/projTwo.vbproj
  artifactory/commands/dotnet/testdata/slnDir/sol.sln
  artifactory/commands/generic/download.go
  artifactory/utils/dependenciestree/dependencies.go
  artifactory/utils/dotnet/configfiletemplate.go
  artifactory/utils/dotnet/dependencies/assetsjson.go
  artifactory/utils/dotnet/dependencies/assetsjson_test.go
  artifactory/utils/dotnet/dependencies/dependencies.go
  artifactory/utils/dotnet/dependencies/packagesconfig.go
  artifactory/utils/dotnet/dependencies/packagesconfig_test.go
  artifactory/utils/dotnet/dependencies/testdata/assetsproject/dep1.nupkg
  artifactory/utils/dotnet/dependencies/testdata/assetsproject/dep2.nupkg
  artifactory/utils/dotnet/dependencies/testdata/assetsproject/obj/project.assets.json
  artifactory/utils/dotnet/dependencies/testdata/packagesproject/localcache/id1/1.0.0/id1.1.0.0.nupkg
  artifactory/utils/dotnet/dependencies/testdata/packagesproject/localcache/id1/1.0.0/id1.nuspec
  artifactory/utils/dotnet/dependencies/testdata/packagesproject/localcache/id2/2.0.0/id2.2.0.0.nupkg
  artifactory/utils/dotnet/dependencies/testdata/packagesproject/localcache/id2/2.0.0/id2.nuspec
  artifactory/utils/dotnet/dependencies/testdata/packagesproject/packages.config
  artifactory/utils/dotnet/solution/project/project.go
  artifactory/utils/dotnet/solution/solution.go
  artifactory/utils/dotnet/solution/solution_test.go
  artifactory/utils/dotnet/solution/testdata/multiprojects.sln
  artifactory/utils/dotnet/solution/testdata/oneproject.sln
  artifactory/utils/dotnet/toolchaincmd.go
  go.mod
  go.sum
  xray/audit/nuget/nuget.go
Labels: improvement

#367 Make all config commands - atomic
  common/commands/config.go
  common/commands/config_test.go
  general/envsetup/envsetup.go
  utils/config/config.go
  utils/config/tokenrefresh.go
  utils/lock/lock.go
Labels: bug

#412 Enhance the 'jf setup' intto message
  general/envsetup/envsetup.go
Labels: improvement

#401 Fix messy logs in 'oc start-build'
  artifactory/commands/oc/startbuild.go
Labels: bug

#411 Add a tree view to artifact deployment
  artifactory/commands/container/push.go
  artifactory/commands/generic/upload.go
  artifactory/commands/golang/gopublish.go
  artifactory/commands/gradle/gradle.go
  artifactory/commands/mvn/mvn.go
  artifactory/commands/utils/result_test.go
  artifactory/utils/filetree.go
  artifactory/utils/filetree_test.go
  go.mod
  go.sum
  utils/coreutils/cmdutils.go
  utils/coreutils/tableutils.go
  utils/coreutils/utils.go
  xray/utils/resultstable.go
Labels: new feature

#418 Change transfer threads number
  artifactory/commands/transfer/settings.go
  artifactory/utils/transfersettings.go
  utils/coreutils/coreconsts.go
  utils/coreutils/utils.go
  xray/utils/downloadindexer.go
Labels: new feature

#407 Audit Yarn
  artifactory/utils/transfersettings.go
  go.mod
  go.sum
  utils/coreutils/coreconsts.go
  utils/coreutils/techutils.go
  utils/coreutils/techutils_test.go
  utils/coreutils/utils.go
  xray/audit/commonutils.go
  xray/audit/yarn/yarn.go
  xray/audit/yarn/yarn_test.go
  xray/commands/audit/generic/auditmanager.go
Labels: new feature

#420 Allow filtering repositories in transfer-config
  artifactory/commands/testdata/config_xmls_exclude_repos/cases/filter-all.xml
  artifactory/commands/testdata/config_xmls_exclude_repos/cases/select-all.xml
  artifactory/commands/testdata/config_xmls_exclude_repos/cases/select-local.xml
  artifactory/commands/testdata/config_xmls_exclude_repos/cases/select-one-from-all.xml
  artifactory/commands/testdata/config_xmls_exclude_repos/cases/select-remote.xml
  artifactory/commands/testdata/config_xmls_exclude_repos/input/artifactory.config.xml
  artifactory/commands/transferconfig/configxmlutils/federatedrepos.go
  artifactory/commands/transferconfig/configxmlutils/fereratedrepos_test.go
  artifactory/commands/transferconfig/configxmlutils/includerepos.go
  artifactory/commands/transferconfig/configxmlutils/includerepos_test.go
  artifactory/commands/transferconfig/configxmlutils/xmlutils.go
  artifactory/commands/transferconfig/transferconfig.go
  artifactory/utils/repositoryutils.go
  utils/coreutils/utils.go
Labels: ignore for release

#421 Get repository names with filters
  artifactory/commands/utils/configfile.go
  artifactory/utils/repositoryutils.go
  artifactory/utils/repositoryutils_test.go
Labels: new feature

#417 New progress bar for the audit command
  go.mod
  go.sum
  utils/ioutils/ioutils.go
  xray/audit/commonutils.go
  xray/audit/go/golang.go
  xray/audit/java/gradle.go
  xray/audit/java/mvn.go
  xray/audit/npm/npm.go
  xray/audit/nuget/nuget.go
  xray/audit/python/python.go
  xray/audit/yarn/yarn.go
  xray/commands/audit/generic/auditmanager.go
  xray/commands/audit/generic/generic.go
Labels: new feature

#425 TransferConfig: Fix 401 in target server verification
  artifactory/commands/transferconfig/transferconfig.go
Labels: ignore for release

#428 offline db sync V3 handle error when downloading URLs
  xray/commands/offlineupdate/offlineupdate.go
Labels: ignore for release

#437 Improve getting transfer errors files
  artifactory/commands/transferfiles/filesdiff.go
  artifactory/commands/transferfiles/transfer.go
  artifactory/commands/transferfiles/utils.go
  artifactory/commands/transferfiles/utils_test.go
Labels: ignore for release
