Repository jfrog/jfrog-cli-core, pull requests merged in 2022-05, with the labels that each got.

#387 Fix scan/docker-scan json output whit progress bar
  xray/commands/scan/scan.go
Labels: bug

#380 Add a build-info UI link to the output of the Build Publish command
  artifactory/commands/buildinfo/publish.go
  artifactory/commands/buildinfo/publish_test.go
  artifactory/formats/buildpublishapi.go
  general/envsetup/envsetup.go
Labels: feature request

#391 Make the 'jf setup' command prompt for a password if needed.
  general/envsetup/envsetup.go
  utils/ioutils/ioutils.go
Labels: ignore for release

#393 Fix audit results overriding issue
  xray/commands/audit/generic/auditmanager.go
Labels: bug

#397 Improvement: setup command
  general/envsetup/envsetup.go
Labels: improvement

#390 Fix: .NET dependencies not found when project is not located under solution directory
  .github/workflows/test.yml
  artifactory/utils/dotnet/solution/project/project.go
  artifactory/utils/dotnet/solution/solution.go
  artifactory/utils/dotnet/solution/solution_test.go
  artifactory/utils/dotnet/solution/testdata/nugetproj/proj1/packages.config
  artifactory/utils/dotnet/solution/testdata/nugetproj/proj1/proj1.cs
  artifactory/utils/dotnet/solution/testdata/nugetproj/proj1/proj1.csproj
  artifactory/utils/dotnet/solution/testdata/nugetproj/proj2/proj2.cs
  artifactory/utils/dotnet/solution/testdata/nugetproj/proj2/proj2.csproj
  artifactory/utils/dotnet/solution/testdata/nugetproj/solutions/nugetproj.sln
  artifactory/utils/dotnet/solution/testdata/nugetproj/solutions/proj2/packages.config
Labels: bug

#400 'jf setup' - The password entered from the trinomial is ignored on Windows
  utils/ioutils/ioutils.go
Labels: bug
