Repository jfrog/jfrog-cli-core, pull requests merged in 2022-10, with the labels that each got.

#566 Transfer - Improve waiting time between phases
  artifactory/commands/transferfiles/filesdiff.go
  artifactory/commands/transferfiles/fileserror.go
  artifactory/commands/transferfiles/fulltransfer.go
  artifactory/commands/transferfiles/manager.go
  artifactory/commands/transferfiles/transfer.go
  artifactory/commands/transferfiles/utils.go
  go.mod
  go.sum
Labels: improvement

#569 Improve stopTransferInArtifactory context comment
  artifactory/commands/transferfiles/utils.go
Labels: ignore for release

#570 Transfer - CTRL+C doesn't shut down the process
  artifactory/commands/transferfiles/filesdiff.go
  artifactory/commands/transferfiles/fileserror.go
  artifactory/commands/transferfiles/fulltransfer.go
  artifactory/commands/transferfiles/manager.go
  artifactory/commands/transferfiles/phase.go
  artifactory/commands/transferfiles/utils.go
Labels: bug

#571 Transfer - Notify pc finished after graceful stop
  artifactory/commands/transferfiles/filesdiff.go
  artifactory/commands/transferfiles/fileserror.go
  artifactory/commands/transferfiles/fulltransfer.go
  artifactory/commands/transferfiles/manager.go
  artifactory/commands/transferfiles/phase.go
  artifactory/commands/transferfiles/phase_test.go
  artifactory/commands/transferfiles/utils.go
Labels: bug

#568 Fix repo create with contentSynchronisation issue
  artifactory/commands/repository/repository.go
Labels: bug

#574 Builder can get stuck on delayed files upload
  artifactory/commands/transferfiles/delayedartifactshandler.go
Labels: bug

#573 Fix TestStopGracefully
  artifactory/commands/transferfiles/phase_test.go
Labels: ignore for release

#582 Fix Scan or Audit output results to file issue
  utils/coreutils/tableutils.go
Labels: bug

#578 Add audit multiple directory support
  xray/commands/audit/generic/auditmanager.go
  xray/commands/audit/generic/generic.go
Labels: improvement

#581 Support new transfer status option
  artifactory/commands/transferfiles/errorshandler_test.go
  artifactory/commands/transferfiles/filesdiff.go
  artifactory/commands/transferfiles/fulltransfer.go
  artifactory/commands/transferfiles/manager.go
  artifactory/commands/transferfiles/phase.go
  artifactory/commands/transferfiles/state.go
  artifactory/commands/transferfiles/state/runstatus.go
  artifactory/commands/transferfiles/state/runstatus_test.go
  artifactory/commands/transferfiles/state/state.go
  artifactory/commands/transferfiles/state/state_test.go
  artifactory/commands/transferfiles/state/statemanager.go
  artifactory/commands/transferfiles/state/statemanager_test.go
  artifactory/commands/transferfiles/state/utils.go
  artifactory/commands/transferfiles/state_test.go
  artifactory/commands/transferfiles/status.go
  artifactory/commands/transferfiles/status_test.go
  artifactory/commands/transferfiles/timeestimation.go
  artifactory/commands/transferfiles/timeestimation_test.go
  artifactory/commands/transferfiles/transfer.go
  artifactory/commands/transferfiles/transfer_test.go
  artifactory/commands/transferfiles/utils.go
  utils/coreutils/coreconsts.go
  utils/coreutils/utils.go
  utils/lock/lock.go
  utils/lock/lock_test.go
Labels: new feature

#583 Fix minor issue in state and add tests
  artifactory/commands/transferfiles/state/state.go
  artifactory/commands/transferfiles/status_test.go
  utils/tests/utils.go
Labels: ignore for release

#588 Fix wrong deleted files count on git-lfs command
  artifactory/commands/generic/gitlfsclean.go
Labels: bug

#590 Transfer - Overcome empty usedSpaceInBytes
  artifactory/commands/transferfiles/transfer.go
Labels: bug

#591 Transfer - Better parsing of repository used space
  artifactory/commands/transferfiles/transfer.go
  artifactory/utils/storageinfo.go
  artifactory/utils/storageinfo_test.go
Labels: bug

#585 Transfer - add transfer failure count to status
  artifactory/commands/transferfiles/errorshandler.go
  artifactory/commands/transferfiles/errorshandler_test.go
  artifactory/commands/transferfiles/fileserror.go
  artifactory/commands/transferfiles/manager.go
  artifactory/commands/transferfiles/state/runstatus.go
  artifactory/commands/transferfiles/state/statemanager.go
  artifactory/commands/transferfiles/status.go
  artifactory/commands/transferfiles/status_test.go
  artifactory/commands/transferfiles/transfer.go
Labels: improvement

#579 Transfer - fix transfer delayed artifacts while having errors
  artifactory/commands/transferfiles/delayedartifactshandler.go
  artifactory/commands/transferfiles/delayedartifactshandler_test.go
  artifactory/commands/transferfiles/filesdiff.go
  artifactory/commands/transferfiles/fileserror.go
  artifactory/commands/transferfiles/fulltransfer.go
  artifactory/commands/transferfiles/manager.go
  artifactory/commands/transferfiles/transfer.go
  utils/coreutils/coreconsts.go
  utils/coreutils/utils.go
Labels: improvement

#596 Fix parsing error when parsing storage size
  artifactory/utils/storageinfo.go
  artifactory/utils/storageinfo_test.go
Labels: bug

#599 Transfer - fix "Transfer failures" status align
  artifactory/commands/transferfiles/status.go
Labels: bug

#600 Transfer - adding retry note to transfer failures status
  artifactory/commands/transferfiles/status.go
  artifactory/commands/transferfiles/transferfileprogress.go
Labels: improvement
