Repository jfrog/jfrog-cli-core, pull requests merged in 2022-08, with the labels that each got.

#476 Refactor CheckResponseStatus usage and update dependencies
  artifactory/commands/buildinfo/buildappend.go
  artifactory/commands/golang/go.go
  artifactory/commands/transferconfig/transferconfig.go
  artifactory/commands/transferfiles/srcpluginservice.go
  artifactory/commands/utils/npmcmdutils.go
  artifactory/utils/container/localagent.go
  general/envsetup/envsetup.go
  go.mod
  go.sum
  missioncontrol/commands/licenseacquire.go
  missioncontrol/commands/licensedeploy.go
  missioncontrol/commands/licenserelease.go
  xray/commands/offlineupdate/offlineupdate.go
Labels: ignore for release

#474 Transfer - do not return from pollUploads on error
  artifactory/commands/transferfiles/manager.go
  artifactory/commands/transferfiles/utils.go
Labels: bug

#477 Transfer - Increase threads limit to 1024
  artifactory/commands/transfer/settings.go
Labels: improvement

#480 Transfer - empty dirs should not have file names
  artifactory/commands/transferfiles/fulltransfer.go
Labels: bug

#456 Added support for 'sarif' format in audit
  artifactory/commands/utils/conditionaluploadutils.go
  go.mod
  go.sum
  utils/coreutils/techutils.go
  xray/audit/commonutils.go
  xray/audit/go/golang.go
  xray/audit/java/gradle.go
  xray/audit/java/mvn.go
  xray/audit/npm/npm.go
  xray/audit/nuget/nuget.go
  xray/audit/python/python.go
  xray/audit/yarn/yarn.go
  xray/formats/simplejsonapi.go
  xray/utils/resultstable.go
  xray/utils/resultwriter.go
  xray/utils/resultwriter_test.go
Labels: new feature

#468 Add pip install support
  utils/coreutils/techutils.go
  utils/coreutils/techutils_test.go
  xray/audit/python/python.go
  xray/audit/python/python_test.go
  xray/commands/audit/generic/auditmanager.go
  xray/commands/audit/generic/generic.go
Labels: new feature

#475 Transfer - remove chunk upload checksum deploy support
  artifactory/commands/transferconfig/transferconfig_test.go
  artifactory/commands/transferfiles/manager.go
  artifactory/commands/transferfiles/srcpluginservice.go
  artifactory/commands/transferfiles/transfer.go
  artifactory/commands/transferfiles/transfer_test.go
  artifactory/commands/transferfiles/utils.go
  common/tests/utils.go
Labels: improvement

#479 Expose transfer variables to allow testing
  artifactory/commands/transferfiles/api.go
  artifactory/commands/transferfiles/filesdiff.go
  artifactory/commands/transferfiles/fulltransfer.go
  artifactory/commands/transferfiles/manager.go
  artifactory/commands/transferfiles/utils.go
  artifactory/utils/transfersettings_test.go
Labels: ignore for release

#482 Transfer - Increase graceful-stop attempts
  artifactory/commands/transferfiles/transfer.go
  artifactory/commands/transferfiles/utils.go
  artifactory/commands/transferfiles/utils_test.go
Labels: improvement

#484 Fix files diff handling range
  artifactory/commands/transferfiles/filesdiff.go
  artifactory/commands/transferfiles/state.go
  artifactory/commands/transferfiles/state_test.go
  artifactory/commands/transferfiles/transfer_test.go
Labels: bug

#483 Config show - make default config to be last and colored
  artifactory/commands/transferfiles/srcpluginservice.go
  common/commands/config.go
Labels: improvement

#487 Fix formatting of log message in Xray offline updates
  xray/commands/offlineupdate/offlineupdate.go
Labels: bug

#464 Config transfer - fail if errors found in the logs
  artifactory/commands/transferconfig/transferconfig.go
Labels: bug

#486 Audit command - Xray version validation and error aggregation
  xray/audit/commonutils.go
  xray/commands/audit/generic/auditmanager.go
  xray/commands/audit/generic/generic.go
  xray/commands/scan/scan.go
  xray/commands/utils.go
  xray/utils/resultwriter.go
Labels: improvement

#488 Fix: Transfer - Include only relevant errors files in summary
  artifactory/commands/transferfiles/errorshandler.go
  artifactory/commands/transferfiles/errorshandler_test.go
  artifactory/commands/transferfiles/filesdiff.go
  artifactory/commands/transferfiles/summary.go
  artifactory/commands/transferfiles/summary_test.go
  artifactory/commands/transferfiles/transfer.go
  artifactory/commands/transferfiles/utils_test.go
  utils/log/log.go
Labels: bug

#490 Transfer - fix plugin not installed message
  artifactory/commands/transferconfig/transferconfig.go
  artifactory/commands/transferfiles/srcpluginservice.go
  artifactory/commands/utils/transfer.go
Labels: bug

#491 Fix: Transfer - Stuck when reaching max tasks
  artifactory/commands/transfer/settings.go
  artifactory/commands/transferfiles/manager.go
  artifactory/commands/transferfiles/transfer.go
  artifactory/commands/transferfiles/utils.go
Labels: bug

#495 Update min data-transfer version to 1.3.1
  artifactory/commands/transferfiles/transfer.go
Labels: breaking change

#503 Remove unnecessary search from interactive selection and replace selection emoji on windows
  common/commands/config.go
  utils/ioutils/promptstrings.go
Labels: improvement

#501 Improve transfer progress bar job type annotation and refactor
  artifactory/commands/transferfiles/filesdiff.go
  artifactory/commands/transferfiles/fulltransfer.go
  artifactory/commands/transferfiles/manager.go
  artifactory/commands/transferfiles/phase.go
  artifactory/commands/transferfiles/propertiesdiff.go
  artifactory/commands/transferfiles/transfer.go
  artifactory/commands/transferfiles/transferfileprogress.go
  artifactory/commands/transferfiles/utils.go
  utils/progressbar/generalprogressbar.go
  utils/progressbar/progressbarmng.go
  utils/progressbar/tasksprogressbar.go
  utils/progressbar/taskswithheadlineprog.go
Labels: improvement

#504 Transfer - Missing repository in the repositories summary
  artifactory/commands/transferfiles/phase.go
  artifactory/commands/transferfiles/propertiesdiff.go
  artifactory/commands/transferfiles/transfer.go
  artifactory/commands/transferfiles/transfer_test.go
  artifactory/commands/transferfiles/transferfileprogress.go
  artifactory/commands/transferfiles/utils.go
  artifactory/utils/storageinfo.go
  artifactory/utils/storageinfo_test.go
  go.mod
  go.sum
Labels: bug

#510 Add data-race detector in tests
  .github/workflows/test.yml
Labels: ignore for release

#502 Add ignore hash check flag when downloading
  artifactory/commands/generic/download.go
  artifactory/utils/download.go
Labels: improvement

#511 Fix login suspension in transfer-config
  artifactory/commands/transferconfig/transferconfig.go
  artifactory/commands/transferconfig/transferconfig_test.go
  go.mod
  go.sum
Labels: bug

#509 transfer-files concurrency improvements on chunk upload tasks for both phases
  artifactory/commands/transferfiles/delayedartifactshandler.go
  artifactory/commands/transferfiles/filesdiff.go
  artifactory/commands/transferfiles/fulltransfer.go
  artifactory/commands/transferfiles/manager.go
  artifactory/commands/transferfiles/phase.go
  artifactory/commands/transferfiles/transfer.go
  artifactory/commands/transferfiles/utils.go
Labels: improvement

#513 Transfer - fix storage info time between retries
  artifactory/utils/storageinfo.go
Labels: bug

#512 Transfer - fix 'invalid phase id' message
  artifactory/commands/transferfiles/transferfileprogress.go
Labels: bug

#515 Update Go to 1.18
  .github/workflows/analysis.yml
  .github/workflows/frogbot-fix.yml
  .github/workflows/frogbot-scan-pr.yml
  .github/workflows/test.yml
  go.mod
  go.sum
Labels: improvement

#517 V1 - Update Go to 1.18
  .github/workflows/test.yml
  go.mod
  go.sum
Labels: improvement

#508 The Maven/Gradle build fails if there is no deployer in the config file
  artifactory/commands/gradle/gradle.go
  artifactory/commands/mvn/mvn.go
  artifactory/utils/buildinfoproperties.go
  utils/gradle/utils.go
  utils/mvn/utils.go
  xray/audit/java/gradle.go
  xray/audit/java/mvn.go
Labels: bug

#521 Fix GetProjectConfFilePath return value
  artifactory/utils/projectconfig.go
Labels: improvement

#516 Avoid old snapshots/tags cleanup after transfer
  artifactory/commands/transferfiles/delayedartifactshandler.go
  artifactory/commands/transferfiles/transfer.go
  artifactory/commands/transferfiles/utils.go
  artifactory/commands/transferfiles/utils_test.go
  go.mod
  go.sum
Labels: bug

#526 Update Dependencies
  .github/workflows/analysis.yml
  artifactory/commands/utils/configfile.go
  general/cisetup/jenkinsfiledslgenerator.go
  go.mod
  go.sum
Labels: improvement

#522 Sync done threads when polling for upload status
  artifactory/commands/transferfiles/api.go
  artifactory/commands/transferfiles/srcpluginservice.go
  artifactory/commands/transferfiles/transfer.go
  artifactory/commands/transferfiles/transfer_test.go
  artifactory/commands/transferfiles/utils.go
  artifactory/commands/transferfiles/utils_test.go
  go.mod
Labels: bug

#523 Allow using snapshot data-transfer versions
  artifactory/commands/transferfiles/transfer.go
  artifactory/commands/transferfiles/transfer_test.go
Labels: ignore for release

#528 Transfer Files - Check CLI and Data Transfer compatibility
  artifactory/commands/transferfiles/srcpluginservice.go
  artifactory/commands/transferfiles/transfer.go
  artifactory/commands/transferfiles/transfer_test.go
Labels: ignore for release

#532 Transfer Files - Fix TestUploadChunkAndPollUploads test
  artifactory/commands/transferfiles/transfer_test.go
Labels: ignore for release

#531 Improve Xray tree build
  go.mod
  go.sum
  xray/audit/commonutils.go
Labels: improvement
