Repository jfrog/jfrog-cli-core, pull requests merged in 2022-07, with the labels that each got.

#444 Transfer - fix delay writer initialization
  artifactory/commands/transferfiles/delayedartifactshandler.go
Labels: ignore for release

#427 Improve error handling on deferred unlock functions
  artifactory/commands/transferconfig/transferconfig_test.go
  artifactory/utils/transfersettings.go
  common/commands/config.go
  utils/config/tokenrefresh.go
  utils/lock/lock.go
  utils/plugins/utils.go
  xray/commands/audit/generic/auditmanager.go
  xray/commands/audit/generic/generic.go
  xray/utils/downloadindexer.go
Labels: improvement

#439 Update config after transfer-config
  artifactory/commands/transferconfig/transferconfig.go
Labels: ignore for release

#442 Fix parsing XML of Artifactory repositories
  artifactory/commands/transferconfig/configxmlutils/includerepos.go
Labels: ignore for release

#451 Failure to calculate final results summary during upload
  go.mod
  go.sum
Labels: bug

#424 Stop filtering npm args on 'jf npm' and improve dependencies code
  .github/workflows/cla.yml
  artifactory/commands/buildinfo/adddependencies.go
  artifactory/commands/buildinfo/addgit.go
  artifactory/commands/container/push.go
  artifactory/commands/dotnet/dotnetcommand.go
  artifactory/commands/generic/createaccesstoken.go
  artifactory/commands/generic/delete.go
  artifactory/commands/golang/go.go
  artifactory/commands/npm/installorci.go
  artifactory/commands/permissiontarget/permissiontarget.go
  artifactory/commands/python/dependencies/dependencies.go
  artifactory/commands/terraform/terraformpublish.go
  artifactory/commands/transferconfig/transferconfig.go
  artifactory/commands/transferconfig/utils_test.go
  artifactory/commands/utils/yarnutils.go
  artifactory/utils/container/buildinfo.go
  common/commands/config.go
  common/commands/curl.go
  general/envsetup/envsetup.go
  general/project/repoutils.go
  utils/config/config.go
  utils/coreutils/cmdutils.go
  utils/ioutils/promptstrings.go
  utils/lock/lock_test.go
  utils/lock/utils_windows.go
Labels: bug

#459 Add unit tests for transfer's "writing errors & delayed artifacts in files" mechanism
  artifactory/commands/transferfiles/delayedartifactshandler.go
  artifactory/commands/transferfiles/delayedartifactshandler_test.go
  artifactory/commands/transferfiles/errorshandler.go
  artifactory/commands/transferfiles/errorshandler_test.go
Labels: ignore for release

#460 Transfer files - reduce chunk size and threads
  artifactory/commands/transferfiles/transfer.go
Labels: improvement

#435 Fix URI calculation on Xray and Artifcatory CURL commands.
  common/commands/curl.go
  common/commands/curl_test.go
Labels: improvement

#462 Show current transfer settings
  artifactory/commands/transfer/settings.go
  artifactory/commands/transferfiles/transfer.go
  artifactory/utils/transfersettings.go
Labels: improvement

#469 Revert "Fix URI calculation on Xray and Artifcatory CURL commands."
  common/commands/curl.go
  common/commands/curl_test.go
Labels: breaking change

#436 Added authentication via mTLS
  common/commands/config.go
  common/commands/config_test.go
  utils/ioutils/ioutils.go
Labels: new feature

#470 Add GetAllTechnologiesList function for audit commands
  utils/coreutils/techutils.go
  xray/commands/audit/generic/auditmanager.go
Labels: ignore for release

#471 Add 'working threads' progress bar to files-transfer command
  artifactory/commands/transfer/settings.go
  artifactory/commands/transferfiles/manager.go
  artifactory/commands/transferfiles/utils.go
  go.sum
  utils/progressbar/progressbarmng.go
  utils/progressbar/transferfileprogressbar.go
Labels: improvement

#473 Fix: Quit 'working threads' progressbar when finished
  artifactory/commands/transferfiles/utils.go
  utils/progressbar/transferfileprogressbar.go
Labels: ignore for release
