Repository jfrog/jfrog-cli-core, pull requests merged in 2023-12, with the labels that each got.

#1056 Update conditions for running contextual analysis scan
  xray/commands/audit/jas/applicability/applicabilitymanager.go
Labels: bug

#1057 Fix - scan SCA recursive only when workingDirs not provided
  xray/commands/audit/scarunner.go
  xray/commands/audit/scarunner_test.go
Labels: bug

#1058 download-jars.sh downloads to the wrong path
  buildscripts/download-jars.sh
Labels: ignore for release

#1060 Refactor- added logs and simplified flow
  xray/commands/audit/sca/go/gloang_test.go
  xray/commands/audit/sca/go/golang.go
  xray/commands/audit/sca/npm/npm.go
  xray/commands/audit/sca/nuget/nuget.go
  xray/commands/audit/sca/yarn/yarn.go
  xray/commands/audit/sca/yarn/yarn_test.go
  xray/commands/audit/scarunner.go
Labels: ignore for release

#1068 Upgraded analyzer manager to version 1.6.0
  xray/utils/analyzermanager.go
Labels: improvement

#1065 WebLogin - Add verification code
  artifactory/utils/weblogin.go
Labels: improvement

#1059 Transfer - Phase 3 progress wrongly adds transferred files
  artifactory/commands/transferfiles/state/statemanager.go
Labels: bug

#1061 Transfer - Make high frequency changes atomic
  artifactory/commands/transferfiles/fileserror.go
  artifactory/commands/transferfiles/state/runstatus.go
  artifactory/commands/transferfiles/state/statemanager.go
  artifactory/commands/transferfiles/state/statemanager_test.go
  artifactory/commands/transferfiles/state/utils.go
  artifactory/commands/transferfiles/status.go
  artifactory/commands/transferfiles/transfer.go
Labels: bug

#1062 Enhance parsing of the maven-dep-tree output
  xray/commands/audit/sca/java/deptreemanager.go
  xray/commands/audit/sca/java/gradle.go
  xray/commands/audit/sca/java/mvn.go
  xray/commands/audit/sca/java/mvn_test.go
Labels: improvement

#1075 Transfer - Generate a thread dump before a graceful stop
  artifactory/commands/transferfiles/transfer.go
  artifactory/utils/weblogin.go
  utils/coreutils/profiler.go
  utils/coreutils/profiler_test.go
Labels: improvement

#1076 Upgrade build-info-go & jfrog-client-go
  go.mod
  go.sum
Labels: ignore for release

#1070 Show sha256 for Xray's DBSyncV3 files to be downloaded
  xray/commands/offlineupdate/offlineupdate.go
  xray/commands/offlineupdate/offlineupdate_test.go
Labels: improvement

#1078 Update dependencies and improve error syntax
  artifactory/commands/buildinfo/addgit.go
  artifactory/commands/golang/go.go
  go.mod
  go.sum
  utils/config/config.go
Labels: ignore for release

#1079 Resolver repo absence fails 'audit' flow
  artifactory/utils/projectconfig.go
Labels: bug

#1080 Upgrade jfrog-client-go to v1.35.2
  go.mod
  go.sum
Labels: ignore for release

#1073 Analyzer manager version update to 1.6.2
  xray/utils/analyzermanager.go
Labels: improvement

#1072 Handle Gradle system properties with spaces
  artifactory/commands/gradle/gradle.go
  go.mod
  go.sum
  utils/gradle/utils.go
Labels: bug

#1085 Upgrade jfrog-client-go & build-info-go
  go.mod
  go.sum
Labels: ignore for release

#1086 Transfer - The runProducerConsumers method might terminate prematurely
  artifactory/commands/transferfiles/manager.go
  artifactory/commands/transferfiles/manager_test.go
  go.mod
  go.sum
Labels: bug

#1088 Transfer - Attempt to transfer ".jfrog" directory in Docker repositories
  artifactory/commands/transferfiles/localgeneratedfilter.go
  artifactory/commands/transferfiles/localgeneratedfilter_test.go
Labels: bug

#1089 Fix memory & time explosion during dependency tree construction for java based projects
  xray/commands/audit/sca/common_test.go
  xray/commands/audit/sca/java/deptreemanager.go
Labels: bug

#1090 Upgrade gofrog & jfrog-client-go
  go.mod
  go.sum
Labels: ignore for release

#1092 Fix wrongly unused maven threads parameter
  artifactory/commands/mvn/mvn.go
  go.mod
  go.sum
Labels: bug

#1093 Promote version to 2.47.9
  go.mod
  go.sum
Labels: ignore for release

#1087 Transfer - Make curProcessedUploadChunks local variable
  artifactory/commands/transferfiles/fulltransfer.go
  artifactory/commands/transferfiles/manager.go
  artifactory/commands/transferfiles/producerconsumer.go
  artifactory/commands/transferfiles/transfer_test.go
  artifactory/commands/transferfiles/utils.go
Labels: ignore for release
