Repository jfrog/jfrog-cli-core, pull requests merged in 2023-07, with the labels that each got.

#850 Transfer config - Avoid deleting existing repos
  artifactory/commands/transferconfig/transferconfig.go
  artifactory/commands/utils/transferconfigbase.go
  artifactory/commands/utils/transferconfigbase_test.go
Labels: bug

#833 Add support for Web Login
  artifactory/utils/weblogin.go
  common/commands/config.go
  common/commands/config_test.go
  general/envsetup/envsetup.go
  general/login/login.go
  general/utils.go
  general/utils_test.go
  go.mod
  go.sum
  utils/config/config.go
Labels: ignore for release

#834 Support environments in repository creation
  artifactory/commands/repository/repository.go
  artifactory/commands/repository/template.go
  artifactory/commands/utils/questionnaire.go
  artifactory/commands/utils/templateutils.go
Labels: new feature

#857 Add support for multiple policy in on block event
  utils/coreutils/tableutils.go
  xray/commands/curation/audit.go
  xray/commands/curation/audit_test.go
Labels: ignore for release

#851 Audit - remove redundant releases remote repo code
  xray/audit/java/gradle.go
  xray/audit/java/gradle_test.go
  xray/audit/java/javautils.go
  xray/audit/java/mvn.go
  xray/audit/java/mvn_test.go
  xray/commands/audit/generic/auditmanager.go
  xray/utils/models.go
Labels: improvement

#861 Align dev branch with master
  go.mod
  go.sum
Labels: ignore for release

#862 Secrets scanners - Enable all scanners
  xray/audit/jas/secretsscanner.go
Labels: ignore for release

#864 Run the scanners independently from the SCA scanner
  xray/audit/jas/applicabilitymanager.go
  xray/audit/jas/iacscanner.go
  xray/audit/jas/secretsscanner.go
  xray/commands/audit/generic/auditmanager.go
  xray/commands/curation/audit.go
  xray/commands/utils/utils.go
Labels: improvement

#866 Change column names in curation audit command
  xray/commands/curation/audit.go
Labels: improvement

#865 Enable Secrets & IaC scanners, add Java Applicability scanning
  go.mod
  xray/audit/jas/applicabilitymanager.go
  xray/audit/jas/secretsscanner.go
  xray/utils/analyzermanager.go
Labels: new feature

#868 Upgrade jfrog-cli-core to 2.39.0
  go.mod
  go.sum
Labels: ignore for release

#869 Update analyzer manager
  xray/utils/analyzermanager.go
Labels: ignore for release

#863 Add technologies contextual analysis support flag
  artifactory/utils/dependenciesutils.go
  utils/coreutils/techutils.go
  utils/coreutils/techutils_test.go
  xray/audit/jas/applicabilitymanager.go
  xray/audit/jas/applicabilitymanager_test.go
  xray/audit/jas/jasmanager.go
  xray/audit/jas/jasmanager_test.go
  xray/commands/audit/generic/auditmanager.go
  xray/commands/audit/generic/generic.go
  xray/utils/analyzermanager.go
  xray/utils/resultstable.go
Labels: improvement

#817 Improve calculation of Npm dependency tree & Aggregate debug log for max depth reached
  xray/audit/commonutils.go
  xray/audit/commonutils_test.go
  xray/audit/npm/npm.go
Labels: improvement

#873 Fix audit results initialize
  xray/audit/jas/jasmanager.go
  xray/audit/jas/jasmanager_test.go
  xray/commands/audit/generic/auditmanager.go
  xray/commands/audit/generic/generic.go
Labels: ignore for release

#871 Return exit code 55 for unsupported OS in Analyzer Manager
  xray/audit/jas/applicabilitymanager.go
  xray/audit/jas/applicabilitymanager_test.go
  xray/audit/jas/iacscanner.go
  xray/audit/jas/secretsscanner.go
  xray/audit/jas/secretsscanner_test.go
  xray/utils/analyzermanager.go
  xray/utils/analyzermanager_test.go
Labels: improvement

#872 Embed gradle-dep-tree JAR in the executable
  .github/workflows/embeded-jar-test.yml
  buildscripts/download-jars.sh
  xray/audit/java/gradle-dep-tree.jar
  xray/audit/java/gradle.go
  xray/audit/java/gradle_test.go
Labels: improvement

#876 Fix typo
  .github/workflows/embedded-jar-test.yml
Labels: ignore for release

#875 Add disable-proxy option to rt replication-create
  artifactory/commands/replication/create.go
  artifactory/commands/replication/template.go
Labels: improvement

#867 New `--module` option added to the `build-add-dependencies` command
  artifactory/commands/buildinfo/adddependencies.go
  go.mod
  go.sum
Labels: improvement

#881 Transfer files - Fix repo snapshot manager error
  artifactory/commands/transferfiles/fulltransfer.go
  utils/reposnapshot/node.go
  utils/reposnapshot/snapshotmanager_test.go
Labels: bug
