Repository jfrog/jfrog-cli-core, pull requests merged in 2023-11, with the labels that each got.

#1014 Improvement to an error message
  xray/commands/audit/sca/npm/npm.go
Labels: ignore for release

#994 Audit SCA recursive scan
  artifactory/commands/buildinfo/adddependencies.go
  go.mod
  go.sum
  utils/coreutils/techutils.go
  utils/coreutils/techutils_test.go
  utils/coreutils/utils.go
  xray/commands/audit/audit.go
  xray/commands/audit/auditparams.go
  xray/commands/audit/jasrunner.go
  xray/commands/audit/jasrunner_test.go
  xray/commands/audit/scarunner.go
  xray/commands/audit/scarunner_test.go
  xray/commands/scan/buildscan.go
  xray/commands/scan/scan.go
  xray/utils/analyzermanager.go
  xray/utils/results.go
  xray/utils/resultstable.go
  xray/utils/resultstable_test.go
  xray/utils/resultwriter.go
Labels: new feature

#1013 Transfer - Fix files count and size after stop
  artifactory/commands/transferfiles/fulltransfer.go
  artifactory/commands/transferfiles/state/state_test.go
  artifactory/commands/transferfiles/state/statemanager.go
  utils/reposnapshot/node.go
  utils/reposnapshot/node_test.go
  utils/reposnapshot/snapshotmanager.go
  utils/reposnapshot/snapshotmanager_test.go
  utils/reposnapshot/testdata/dummy-repo-local
Labels: bug

#1016 Transfer - Snapshot may be incomplete
  artifactory/commands/transferfiles/fulltransfer.go
  artifactory/commands/transferfiles/state/transfersnapshot.go
  utils/reposnapshot/node.go
Labels: bug

#1018 Transfer config - Precheck for Docker repo names
  artifactory/commands/transferconfig/transferconfig.go
  artifactory/commands/transferconfig/transferconfig_test.go
  artifactory/commands/transferconfigmerge/transferconfigmerge.go
  artifactory/commands/transferfiles/longpropertycheck.go
  artifactory/commands/transferfiles/longpropertycheck_test.go
  artifactory/commands/transferfiles/transfer.go
  artifactory/commands/utils/precheckrunner/checkrunner.go
  artifactory/commands/utils/precheckrunner/checkrunner_test.go
  artifactory/commands/utils/precheckrunner/remoteurlchecker.go
  artifactory/commands/utils/precheckrunner/remoteurlchecker_test.go
  artifactory/commands/utils/precheckrunner/repositorynamingchecker.go
  artifactory/commands/utils/precheckrunner/repositorynamingchecker_test.go
  artifactory/commands/utils/precheckrunner/testdata/remoteurlchecker/nuget_repo.json
  artifactory/commands/utils/transferconfigbase.go
  artifactory/commands/utils/transferconfigbase_test.go
Labels: improvement

#1019 Promote dependencies for release
  artifactory/commands/dotnet/dotnetcommand_test.go
  go.mod
  go.sum
  xray/commands/curation/curationaudit.go
Labels: ignore for release

#1021 Xray SCA scan - always show results with location on Sarif output
  xray/utils/resultwriter.go
  xray/utils/resultwriter_test.go
Labels: bug

#1020 Build append fails with special characters
  artifactory/commands/buildinfo/buildappend.go
  go.mod
  go.sum
Labels: bug

#1022 Add .git to audit default exclusions
  xray/commands/audit/scarunner.go
  xray/commands/audit/scarunner_test.go
Labels: improvement

#1024 Audit - ignore config file when needed + add releaserepo for maven
  artifactory/utils/projectconfig.go
  go.mod
  go.sum
Labels: bug

#1027 Refine gradle projects indicators
  utils/coreutils/techutils.go
Labels: improvement

#1029 Tweak JAS exclude patterns
  xray/commands/audit/jas/common.go
Labels: improvement

#1028 SCA scan - Remove space in default descriptor
  xray/utils/resultwriter.go
  xray/utils/resultwriter_test.go
Labels: bug

#1033 New Yarn tech detection indicator
  utils/coreutils/techutils.go
Labels: improvement

#1030 Audit - Sarif output, show default location for license violation
  xray/utils/resultstable.go
  xray/utils/resultwriter.go
  xray/utils/resultwriter_test.go
Labels: improvement

#1015 Yarn- Enhancements to Artifactory Integration and auto-installation for yarn projects
  artifactory/commands/utils/npmcmdutils.go
  artifactory/commands/yarn/yarn.go
  go.mod
  go.sum
  xray/commands/audit/sca/yarn/yarn.go
  xray/commands/audit/sca/yarn/yarn_test.go
  xray/commands/audit/scarunner.go
  xray/commands/testdata/yarn-project/.pnp.cjs
  xray/commands/testdata/yarn-project/package.json
Labels: improvement

#1036 Transfer - AQL optimizations
  artifactory/commands/transferfiles/filediff_test.go
  artifactory/commands/transferfiles/filesdiff.go
  artifactory/commands/transferfiles/fulltransfer.go
  artifactory/commands/transferfiles/phase.go
  artifactory/commands/transferfiles/transfer.go
Labels: improvement

#1037 Fix settings.xml template for maven-dep-tree
  artifactory/utils/projectconfig.go
  xray/commands/audit/sca/java/deptreemanager.go
  xray/commands/audit/sca/java/gradle.go
  xray/commands/audit/sca/java/gradle_test.go
  xray/commands/audit/sca/java/mvn.go
  xray/commands/audit/sca/java/mvn_test.go
  xray/commands/audit/sca/java/resources/settings.xml
  xray/commands/curation/curationaudit_test.go
Labels: ignore for release

#1034 Fix issues in Maven and Gradle wrapper config
  artifactory/commands/utils/configfile.go
Labels: bug

#1042 Blocking dependencies resolution from Artifactory for Yarn V1 and Yarn V4
  xray/commands/audit/sca/yarn/yarn.go
Labels: bug

#1032 Transfer - Limit max AQL threads to 16
  artifactory/commands/transferfiles/manager.go
  artifactory/commands/transferfiles/transfer.go
  artifactory/commands/transferfiles/transfer_test.go
  artifactory/commands/transferfiles/utils.go
  artifactory/commands/transferfiles/utils_test.go
  artifactory/utils/transfersettings.go
Labels: improvement

#1043 Transfer - Improve time estimation algorithm
  artifactory/commands/transferfiles/state/runstatus.go
  artifactory/commands/transferfiles/state/statemanager.go
  artifactory/commands/transferfiles/state/statemanager_test.go
  artifactory/commands/transferfiles/state/timeestimation.go
  artifactory/commands/transferfiles/state/timeestimation_test.go
  artifactory/commands/transferfiles/status.go
  artifactory/commands/transferfiles/status_test.go
  artifactory/commands/transferfiles/transfer.go
  utils/progressbar/transferprogressbarmanager.go
Labels: improvement

#1044 Transfer - Fix and improve long props check
  artifactory/commands/transferfiles/filesdiff.go
  artifactory/commands/transferfiles/fulltransfer.go
  artifactory/commands/transferfiles/longpropertycheck.go
  artifactory/commands/transferfiles/longpropertycheck_test.go
  artifactory/commands/transferfiles/transfer.go
  artifactory/commands/transferfiles/utils.go
  artifactory/commands/utils/precheckrunner/remoteurlchecker.go
Labels: improvement

#1039 Upgrade the Analyzer Manager component to version 1.4.0
  xray/utils/analyzermanager.go
Labels: improvement

#1031 Support for Distribution path mapping with AQL
  common/spec/specfiles.go
  go.mod
  go.sum
Labels: new feature

#1051 Update go.mod and go.sum
  go.mod
  go.sum
Labels: ignore for release

#1047 Enhancements in Output Control Options for Scan Results Writer
  xray/utils/resultwriter.go
Labels: improvement

#1040 .Net/NuGet- Enhancements to Artifactory Integration and auto-installation for .NET/NuGet projects
  artifactory/utils/projectconfig.go
  go.mod
  go.sum
  xray/commands/audit/sca/nuget/nuget.go
  xray/commands/audit/sca/nuget/nuget_test.go
  xray/commands/audit/scarunner.go
  xray/commands/testdata/dotnet-projects/dotnet-multi/ClassLibrary1/ClassLibrary1.csproj
  xray/commands/testdata/dotnet-projects/dotnet-multi/SharedProject1/SharedProject1.projitems
  xray/commands/testdata/dotnet-projects/dotnet-multi/SharedProject1/SharedProject1.shproj
  xray/commands/testdata/dotnet-projects/dotnet-multi/TestApp1/TestApp1.csproj
  xray/commands/testdata/dotnet-projects/dotnet-multi/TestSolution.sln
  xray/commands/testdata/dotnet-projects/dotnet-single/Class1.cs
  xray/commands/testdata/dotnet-projects/dotnet-single/dotnet-single.csproj
  xray/utils/auditbasicparams.go
Labels: improvement

#1046 Xray usage event report
  utils/usage/usage.go
  utils/usage/usage_test.go
Labels: ignore for release

#1055 Revert "Enhancements in Output Control Options for Scan Results Writer"
  xray/utils/resultwriter.go
Labels: ignore for release
