Repository jfrog/jfrog-cli-core, pull requests merged in 2023-01, with the labels that each got.

#652 Transfer - fix possible race when finding directory node
  artifactory/commands/transferfiles/status_test.go
  utils/reposnapshot/node.go
  utils/reposnapshot/snapshotmanager.go
  utils/reposnapshot/snapshotmanager_test.go
Labels: ignore for release

#651 Fix npm version log string
  xray/audit/npm/npm.go
Labels: bug

#655 Add Go version to audit-go dependency tree
  go.mod
  go.sum
  utils/golang/utils.go
  xray/audit/go/gloang_test.go
  xray/audit/go/golang.go
Labels: new feature

#656 Extract splitComponentId and add newline in the alerts summary
  artifactory/utils/storageinfo_test.go
  xray/utils/resultstable.go
  xray/utils/resultstable_test.go
  xray/utils/resultwriter.go
  xray/utils/resultwriter_test.go
Labels: improvement

#658 Unite all minimum version validation functions
  artifactory/commands/container/containermanagerbase.go
  artifactory/commands/golang/gopublish.go
  artifactory/commands/transferconfig/transferconfig.go
  artifactory/commands/transferconfig/transferconfig_test.go
  artifactory/commands/transferfiles/transfer.go
  artifactory/commands/transferfiles/transfer_test.go
  artifactory/commands/utils/npmcmdutils.go
  artifactory/utils/container/containermanager.go
  utils/coreutils/utils.go
  xray/audit/commonutils.go
  xray/commands/scan/buildscan.go
  xray/commands/scan/dockerscan.go
  xray/commands/scan/scan.go
  xray/commands/utils.go
Labels: ignore for release, improvement

#659 Unite all minimum version validation functions
  artifactory/commands/transferfiles/transfer.go
  artifactory/commands/transferfiles/transfer_test.go
  artifactory/utils/container/containermanager.go
Labels: ignore for release

#637 Fail audit command for yarn v1
  xray/audit/commonutils.go
  xray/audit/python/python.go
  xray/audit/yarn/yarn.go
Labels: bug

#662 Change convert scan to sarif headline
  xray/utils/resultwriter.go
  xray/utils/resultwriter_test.go
Labels: improvement

#663 Unite all Create CSV File functions
  artifactory/commands/transferfiles/errorshandler.go
  artifactory/commands/transferfiles/longpropertycheck.go
  artifactory/commands/transferfiles/summary.go
  artifactory/commands/transferfiles/summary_test.go
  artifactory/commands/transferfiles/transfer.go
  artifactory/commands/transferfiles/transfer_test.go
  artifactory/commands/utils/remoteurlchecker.go
  artifactory/commands/utils/transfer.go
Labels: ignore for release

#665 Convert Repository Filter to Generic Filter
  artifactory/commands/buildinfo/buildappend.go
  artifactory/commands/transferconfig/configxmlutils/includerepos.go
  artifactory/commands/transferconfig/configxmlutils/includerepos_test.go
  artifactory/commands/transferconfig/transferconfig.go
  artifactory/utils/repositoryutils.go
  artifactory/utils/repositoryutils_test.go
Labels: ignore for release

#664 Use server from Terraform project configuration
  artifactory/commands/terraform/terraformpublish.go
  artifactory/commands/terraform/terraformpublish_test.go
Labels: bug

#666 Install Transfer Plugin - Support Artifactory product folder names with prefix/suffix
  artifactory/commands/transferinstall/datatransferinstall.go
  artifactory/commands/transferinstall/datatransferinstall_test.go
Labels: bug

#667 Transfer - Allow stopping from a different process
  artifactory/commands/transferfiles/manager.go
  artifactory/commands/transferfiles/phase.go
  artifactory/commands/transferfiles/status.go
  artifactory/commands/transferfiles/transfer.go
  artifactory/commands/transferfiles/transfer_test.go
  artifactory/commands/transferfiles/utils.go
  artifactory/commands/transferfiles/utils_test.go
Labels: improvement

#669 Transfer - Count skipped files in the progress bar
  artifactory/commands/transferfiles/manager.go
  artifactory/commands/transferfiles/state/state_test.go
  artifactory/commands/transferfiles/state/statemanager.go
  artifactory/commands/transferfiles/state/statemanager_test.go
  artifactory/commands/transferfiles/state/timeestimation_test.go
  artifactory/commands/transferfiles/status_test.go
  artifactory/commands/transferfiles/transferfileprogress.go
  artifactory/utils/transfersettings.go
  utils/progressbar/progressbarmng.go
Labels: improvement

#672 Transfer - Close the stop file after creation
  artifactory/commands/transferfiles/transfer.go
  utils/reposnapshot/snapshotmanager_test.go
Labels: bug

#668 Searching JFrog config shouldn't return a permission denied error
  artifactory/utils/buildutils.go
  artifactory/utils/buildutils_test.go
Labels: bug

#657 New command - Transfer config merge
  .github/workflows/test.yml
  artifactory/commands/transferconfig/transferconfig.go
  artifactory/commands/transferconfig/transferconfig_test.go
  artifactory/commands/transferconfig/transferconfigmerge.go
  artifactory/commands/transferconfig/transferconfigmerge_test.go
  artifactory/commands/transferfiles/status.go
  artifactory/commands/transferinstall/datatransferinstall.go
  common/commands/config.go
  go.mod
  go.sum
  utils/coreutils/cmdutils.go
  utils/coreutils/utils.go
Labels: new feature

#673 Add static analysis to test files
  .github/workflows/analysis.yml
  artifactory/commands/npm/installorci_test.go
  artifactory/commands/transferconfig/transferconfig_test.go
  artifactory/commands/transferfiles/phase_test.go
  artifactory/commands/transferfiles/transfer_test.go
  artifactory/commands/transferfiles/utils_test.go
  general/envsetup/envsetup_test.go
  utils/config/configtoken_test.go
  utils/coreutils/cmdutils_test.go
  xray/audit/nuget/nuget_test.go
Labels: ignore for release

#670 Transfer - reflect transferred units from snapshot in progress
  artifactory/commands/transferfiles/fulltransfer.go
  artifactory/commands/transferfiles/state/statemanager.go
  artifactory/commands/transferfiles/transfer.go
  artifactory/commands/transferfiles/transferfileprogress.go
Labels: bug

#677 Transfer config merge admin token validation
  artifactory/commands/transferconfig/transferconfigmerge.go
Labels: ignore for release

#630 Pipelines Commands
  artifactory/commands/transferfiles/state/timeestimation_test.go
  pipelines/commands/status.go
  pipelines/commands/status_test.go
  pipelines/commands/sync.go
  pipelines/commands/syncstatus.go
  pipelines/commands/syncstatus_test.go
  pipelines/commands/trigger.go
  pipelines/commands/version.go
  pipelines/manager/manager.go
  pipelines/status/status.go
  pipelines/status/status_test.go
Labels: new feature

#680 Handle API key used as Access Token
  common/commands/config.go
  common/commands/config_test.go
  go.mod
  go.sum
Labels: improvement

#671 Improve audit table display
  xray/formats/conversion.go
  xray/formats/simplejsonapi.go
  xray/formats/table.go
  xray/utils/resultstable.go
  xray/utils/resultstable_test.go
  xray/utils/resultwriter.go
  xray/utils/resultwriter_test.go
Labels: improvement

#682 Extract SplitScanResults
  xray/utils/resultwriter.go
Labels: improvement
