Repository jfrog/jfrog-cli-core, pull requests merged in 2023-03, with the labels that each got.

#700 Update dependencies
  go.mod
  go.sum
Labels: dependencies

#689 Transfer config - Improve repositories transfer
  artifactory/commands/testdata/config_xmls_federated_repos/expected/artifactory.config-0.xml
  artifactory/commands/testdata/config_xmls_federated_repos/expected/artifactory.config-1.xml
  artifactory/commands/testdata/config_xmls_federated_repos/expected/artifactory.config-2.xml
  artifactory/commands/testdata/config_xmls_federated_repos/expected/artifactory.config-3.xml
  artifactory/commands/testdata/config_xmls_federated_repos/expected/artifactory.config-4.xml
  artifactory/commands/testdata/config_xmls_federated_repos/expected/artifactory.config-5.xml
  artifactory/commands/testdata/config_xmls_federated_repos/input/artifactory.config-0.xml
  artifactory/commands/testdata/config_xmls_federated_repos/input/artifactory.config-1.xml
  artifactory/commands/testdata/config_xmls_federated_repos/input/artifactory.config-2.xml
  artifactory/commands/testdata/config_xmls_federated_repos/input/artifactory.config-3.xml
  artifactory/commands/testdata/config_xmls_federated_repos/input/artifactory.config-4.xml
  artifactory/commands/testdata/config_xmls_federated_repos/input/artifactory.config-5.xml
  artifactory/commands/transferconfig/configxmlutils/federatedrepos.go
  artifactory/commands/transferconfig/configxmlutils/fereratedrepos_test.go
  artifactory/commands/transferconfig/configxmlutils/xmlutils.go
  artifactory/commands/transferconfig/configxmlutils/xmlutils_test.go
  artifactory/commands/transferconfig/transferconfig.go
  artifactory/commands/transferconfig/transferconfig_test.go
  artifactory/commands/transferconfigmerge/transferconfigmerge.go
  artifactory/commands/transferconfigmerge/transferconfigmerge_test.go
  artifactory/commands/utils/testdata/transferconfig/federated_repo.json
  artifactory/commands/utils/testdata/transferconfig/federated_repo_without_members.json
  artifactory/commands/utils/transferconfigbase.go
  artifactory/commands/utils/transferconfigbase_test.go
  artifactory/commands/utils/transferconfigutils.go
  artifactory/commands/utils/transferconfigutils_test.go
  artifactory/utils/repositoryutils.go
Labels: improvement

#696 Add new attributes to technologiesData
  utils/coreutils/techutils.go
Labels: improvement

#687 Enhancements to the progress bars code
  artifactory/commands/transferfiles/filesdiff.go
  artifactory/commands/transferfiles/fileserror.go
  artifactory/commands/transferfiles/fulltransfer.go
  artifactory/commands/transferfiles/manager.go
  artifactory/commands/transferfiles/state/state.go
  artifactory/commands/transferfiles/state/statemanager.go
  artifactory/commands/transferfiles/state/timeestimation_test.go
  artifactory/commands/transferfiles/transfer.go
  artifactory/commands/transferfiles/transferfileprogress.go
  utils/progressbar/progressbarmng.go
  utils/progressbar/transferprogressbarmanager.go
Labels: improvement

#701 Unreleased Bug - Gitlab Audit
  xray/utils/resultstable.go
Labels: ignore for release

#690 Improve deps resolution and refactor audit
  artifactory/commands/dotnet/dotnetcommand.go
  artifactory/commands/dotnet/dotnetcommand_test.go
  artifactory/commands/golang/go.go
  artifactory/commands/golang/go_test.go
  artifactory/commands/gradle/gradle.go
  artifactory/commands/mvn/mvn.go
  artifactory/commands/npm/common.go
  artifactory/commands/npm/generic.go
  artifactory/commands/npm/installorci.go
  artifactory/commands/python/pip.go
  artifactory/commands/python/poetry.go
  artifactory/commands/python/python.go
  artifactory/commands/yarn/yarn.go
  artifactory/commands/yarn/yarn_test.go
  artifactory/utils/buildinfoproperties.go
  artifactory/utils/buildinfoproperties_test.go
  artifactory/utils/dependenciesutils.go
  artifactory/utils/npm/config-list.go
  utils/golang/utils.go
  utils/golang/utils_test.go
  utils/gradle/utils.go
  utils/mvn/utils.go
  utils/python/utils.go
  utils/python/utils_test.go
  xray/audit/go/gloang_test.go
  xray/audit/go/golang.go
  xray/audit/java/gradle.go
  xray/audit/java/gradle_test.go
  xray/audit/java/javautils.go
  xray/audit/java/mvn.go
  xray/audit/java/mvn_test.go
  xray/audit/python/python.go
  xray/audit/python/python_test.go
  xray/commands/audit/generic/auditmanager.go
  xray/commands/audit/generic/generic.go
Labels: improvement

#702 Improve npm install command log
  artifactory/commands/npm/installorci.go
Labels: improvement

#707 Fix build scan Sarif format and remove redundant scan context message
  .github/workflows/test.yml
  go.mod
  go.sum
  xray/commands/scan/buildscan.go
  xray/utils/resultstable.go
  xray/utils/resultwriter.go
  xray/utils/resultwriter_test.go
Labels: bug

#681 Use wrapper by default in audit maven & gradle
  go.mod
  go.sum
  utils/mvn/utils.go
  xray/audit/java/javautils.go
  xray/audit/java/mvn.go
  xray/audit/java/mvn_test.go
  xray/commands/testdata/maven-example-with-wrapper/.mvn/wrapper/MavenWrapperDownloader.java
  xray/commands/testdata/maven-example-with-wrapper/.mvn/wrapper/maven-wrapper.jar
  xray/commands/testdata/maven-example-with-wrapper/.mvn/wrapper/maven-wrapper.properties
  xray/commands/testdata/maven-example-with-wrapper/multi1/pom.xml
  xray/commands/testdata/maven-example-with-wrapper/multi1/src/main/java/artifactory/test/Multi1.java
  xray/commands/testdata/maven-example-with-wrapper/multi1/src/test/java/artifactory/test/AppTest.java
  xray/commands/testdata/maven-example-with-wrapper/multi1/target/classes/artifactory/test/Multi1.class
  xray/commands/testdata/maven-example-with-wrapper/multi1/target/maven-status/maven-compiler-plugin/compile/default-compile/createdFiles.lst
  xray/commands/testdata/maven-example-with-wrapper/multi1/target/maven-status/maven-compiler-plugin/compile/default-compile/inputFiles.lst
  xray/commands/testdata/maven-example-with-wrapper/multi1/target/maven-status/maven-compiler-plugin/testCompile/default-testCompile/createdFiles.lst
  xray/commands/testdata/maven-example-with-wrapper/multi1/target/maven-status/maven-compiler-plugin/testCompile/default-testCompile/inputFiles.lst
  xray/commands/testdata/maven-example-with-wrapper/multi1/target/test-classes/artifactory/test/AppTest.class
  xray/commands/testdata/maven-example-with-wrapper/multi2/pom.xml
  xray/commands/testdata/maven-example-with-wrapper/multi2/src/main/java/artifactory/test/App.java
  xray/commands/testdata/maven-example-with-wrapper/multi2/src/test/java/artifactory/test/AppTest.java
  xray/commands/testdata/maven-example-with-wrapper/multi2/target/classes/artifactory/test/App.class
  xray/commands/testdata/maven-example-with-wrapper/multi2/target/maven-status/maven-compiler-plugin/compile/default-compile/createdFiles.lst
  xray/commands/testdata/maven-example-with-wrapper/multi2/target/maven-status/maven-compiler-plugin/compile/default-compile/inputFiles.lst
  xray/commands/testdata/maven-example-with-wrapper/multi2/target/maven-status/maven-compiler-plugin/testCompile/default-testCompile/createdFiles.lst
  xray/commands/testdata/maven-example-with-wrapper/multi2/target/maven-status/maven-compiler-plugin/testCompile/default-testCompile/inputFiles.lst
  xray/commands/testdata/maven-example-with-wrapper/multi2/target/test-classes/artifactory/test/AppTest.class
  xray/commands/testdata/maven-example-with-wrapper/multi3/pom.xml
  xray/commands/testdata/maven-example-with-wrapper/multi3/src/main/java/artifactory/test/Multi3.java
  xray/commands/testdata/maven-example-with-wrapper/multi3/src/main/webapp/WEB-INF/web.xml
  xray/commands/testdata/maven-example-with-wrapper/multi3/src/test/java/artifactory/test/AppTest.java
  xray/commands/testdata/maven-example-with-wrapper/multi3/target/classes/artifactory/test/Multi3.class
  xray/commands/testdata/maven-example-with-wrapper/multi3/target/maven-status/maven-compiler-plugin/compile/default-compile/createdFiles.lst
  xray/commands/testdata/maven-example-with-wrapper/multi3/target/maven-status/maven-compiler-plugin/compile/default-compile/inputFiles.lst
  xray/commands/testdata/maven-example-with-wrapper/multi3/target/maven-status/maven-compiler-plugin/testCompile/default-testCompile/createdFiles.lst
  xray/commands/testdata/maven-example-with-wrapper/multi3/target/maven-status/maven-compiler-plugin/testCompile/default-testCompile/inputFiles.lst
  xray/commands/testdata/maven-example-with-wrapper/multi3/target/test-classes/artifactory/test/AppTest.class
  xray/commands/testdata/maven-example-with-wrapper/mvnw
  xray/commands/testdata/maven-example-with-wrapper/mvnw.cmd
  xray/commands/testdata/maven-example-with-wrapper/pom.xml
Labels: improvement

#708 Transfer - Add logs for threads polling
  artifactory/commands/transferfiles/utils.go
Labels: improvement

#711 Upgrade dependencies
  go.mod
  go.sum
Labels: ignore for release

#714 Fix audit multiple technologies issue
  xray/commands/audit/generic/auditmanager.go
Labels: bug

#715 Improve wrong server id log
  common/commands/config.go
  utils/lock/lock.go
Labels: ignore for release

#716 Update dependencies
  go.mod
  go.sum
Labels: ignore for release

#705 Transfer - Reduce snapshot memory consumption
  artifactory/commands/transferfiles/fulltransfer.go
  artifactory/commands/transferfiles/state/runstatus.go
  artifactory/commands/transferfiles/state/runstatus_test.go
  artifactory/commands/transferfiles/state/state.go
  artifactory/commands/transferfiles/state/state_test.go
  artifactory/commands/transferfiles/state/statemanager.go
  artifactory/commands/transferfiles/state/utils.go
  artifactory/commands/transferfiles/transfer.go
  artifactory/commands/transferfiles/utils.go
  utils/reposnapshot/node.go
  utils/reposnapshot/node_test.go
  utils/reposnapshot/snapshotmanager.go
  utils/reposnapshot/snapshotmanager_test.go
  utils/reposnapshot/testdata/dummy-repo-local
Labels: breaking change, improvement

#720 Transfer - If plugin not install log information
  artifactory/commands/transferfiles/transfer.go
Labels: ignore for release

#722 Docker - Skip build-info if there are no image layers in Artifactory
  artifactory/utils/container/buildinfo.go
  artifactory/utils/container/buildinfo_test.go
  artifactory/utils/container/localagent.go
Labels: bug

#712 Avoid adding the configfile argument to dotnet test command
  artifactory/commands/dotnet/dotnetcommand.go
  artifactory/commands/dotnet/dotnetcommand_test.go
Labels: bug

#726 Fix CLA trigger
  .github/workflows/cla.yml
  go.mod
  go.sum
Labels: ignore for release

#725 Config transfer - support checking remote repos in Artifactory >= 7.49
  artifactory/commands/transferconfig/transferconfig.go
  artifactory/commands/utils/remoteurlchecker.go
  artifactory/commands/utils/remoteurlchecker_test.go
  artifactory/commands/utils/testdata/remoteurlchecker/nuget_repo.json
  go.mod
  go.sum
Labels: improvement
