Repository jfrog/jfrog-cli-core, pull requests merged in 2023-06, with the labels that each got.

#763 Transfer config - allow providing the src work dir
  artifactory/commands/transferconfig/transferconfig.go
  artifactory/commands/transferconfig/transferconfig_test.go
Labels: improvement

#815 Transfer - Missing files in large repositories
  artifactory/commands/transferfiles/fulltransfer.go
Labels: bug

#816 Contextual analysis - add arm64 arch support
  utils/coreutils/utils.go
Labels: bug

#759 Transfer - Support transferring directories' props
  artifactory/commands/transferfiles/api/types.go
  artifactory/commands/transferfiles/filesdiff.go
  artifactory/commands/transferfiles/fulltransfer.go
  artifactory/commands/transferfiles/localgeneratedfilter.go
  artifactory/commands/transferfiles/state/statemanager.go
  artifactory/commands/transferfiles/state/timeestimation_test.go
  artifactory/commands/transferfiles/utils.go
Labels: improvement

#818 `jf audit` generates invalid JSON format
  xray/commands/audit/generic/generic.go
  xray/commands/scan/buildscan.go
  xray/commands/scan/scan.go
  xray/utils/resultwriter.go
Labels: bug

#806 Fix switch statements and cleanup code
  artifactory/commands/repository/template.go
  artifactory/commands/transferfiles/delayedartifactshandler.go
  general/cisetup/utils.go
  utils/progressbar/progressbarmng.go
Labels: ignore for release

#796 Support creating federated repositories by CLI
  artifactory/commands/repository/repository.go
  artifactory/commands/repository/template.go
Labels: new feature

#821 Transfer - Limit local generated filter requests
  artifactory/commands/transferfiles/localgeneratedfilter.go
  artifactory/commands/transferfiles/localgeneratedfilter_test.go
  artifactory/commands/transferfiles/phase.go
  artifactory/commands/transferfiles/transfer.go
Labels: improvement

#823 Transfer - Disable repo snapshot for delayed files
  artifactory/commands/transferfiles/fulltransfer.go
Labels: improvement

#824 Upgrade jfrog-client-go to v1.30.0
  go.mod
  go.sum
Labels: ignore for release

#820 Use releases server-id from the environment variable
  xray/audit/java/gradle.go
  xray/audit/java/gradle_test.go
Labels: bug

#775 New `--include` option for `jf rt search`
  artifactory/commands/generic/generic.go
  artifactory/utils/search.go
  common/spec/builder.go
  common/spec/specfiles.go
  go.mod
  go.sum
Labels: new feature

#788 JFrog Advanced Security - Secrets & IaC scans
  xray/audit/jas/applicabilitymanager.go
  xray/audit/jas/applicabilitymanager_test.go
  xray/audit/jas/iacscanner.go
  xray/audit/jas/iacscanner_test.go
  xray/audit/jas/jasmanager.go
  xray/audit/jas/jasmanager_test.go
  xray/audit/jas/secretsscanner.go
  xray/audit/jas/secretsscanner_test.go
  xray/commands/audit/generic/generic.go
  xray/commands/testdata/iac-scan/contains-iac-violations.sarif
  xray/commands/testdata/iac-scan/no-violations.sarif
  xray/commands/testdata/secrets-scan/contain-secrets.sarif
  xray/commands/testdata/secrets-scan/no-secrets.sarif
  xray/formats/conversion.go
  xray/formats/simplejsonapi.go
  xray/formats/table.go
  xray/utils/analyzermanager.go
  xray/utils/analyzermanager_test.go
  xray/utils/resultstable.go
  xray/utils/resultstable_test.go
  xray/utils/resultwriter.go
Labels: new feature

#828 Remove redundant space in download dependency log
  artifactory/utils/dependenciesutils.go
Labels: ignore for release

#819 Reorganize audit code
  utils/coreutils/utils.go
  xray/commands/audit/generic/auditmanager.go
  xray/commands/audit/generic/generic.go
  xray/utils/resultstable.go
  xray/utils/resultwriter.go
  xray/utils/resultwriter_test.go
Labels: improvement

#829 Audit - Add Secrets & IaC to sarif format
  artifactory/utils/dependenciesutils.go
  xray/commands/utils/utils_test.go
  xray/utils/resultstable.go
  xray/utils/resultstable_test.go
  xray/utils/resultwriter.go
  xray/utils/resultwriter_test.go
Labels: improvement

#837 Transfer - Exclude transferring the repository props
  artifactory/commands/transferfiles/fulltransfer.go
Labels: improvement

#838 Transfer - Missing diffs in large diffs
  artifactory/commands/transferfiles/filesdiff.go
Labels: bug

#839 Transfer - Empty dirs are not transferred in diffs
  artifactory/commands/transferfiles/filediff_test.go
  artifactory/commands/transferfiles/filesdiff.go
Labels: bug

#841 Fix GenerateSarifFromScan test
  xray/utils/resultwriter_test.go
Labels: ignore for release

#846 Audit - Remove irrelevant column from IaC and Secrets scan
  xray/commands/audit/generic/generic.go
  xray/formats/conversion.go
  xray/formats/table.go
  xray/utils/resultwriter.go
  xray/utils/resultwriter_test.go
Labels: ignore for release

#845 Fix analyzer manager download from remote repository
  artifactory/utils/dependenciesutils.go
  utils/config/config.go
  utils/coreutils/utils.go
  xray/utils/analyzermanager.go
Labels: bug

#843 Transfer - Make errors and delays file names unique
  artifactory/commands/transferfiles/delayedartifactshandler.go
  artifactory/commands/transferfiles/errorshandler.go
  artifactory/commands/transferfiles/errorshandler_test.go
  artifactory/commands/transferfiles/utils.go
  artifactory/commands/transferfiles/utils_test.go
Labels: bug

#849 Transfer - Show stale chunks in --status
  artifactory/commands/transferfiles/manager.go
  artifactory/commands/transferfiles/state/runstatus.go
  artifactory/commands/transferfiles/state/statemanager.go
  artifactory/commands/transferfiles/state/timeestimation.go
  artifactory/commands/transferfiles/state/utils.go
  artifactory/commands/transferfiles/state/utils_test.go
  artifactory/commands/transferfiles/status.go
  artifactory/commands/transferfiles/status_test.go
  artifactory/commands/transferfiles/utils.go
  artifactory/commands/transferfiles/utils_test.go
Labels: improvement

#773 Add Support for Release Bundles Create and Promote
  artifactory/utils/utils.go
  go.mod
  go.sum
  lifecycle/common.go
  lifecycle/createcommon.go
  lifecycle/createfrombuilds.go
  lifecycle/createfrombundles.go
  lifecycle/promote.go
  utils/config/config.go
Labels: feature request
