Repository jfrog/jfrog-cli-core, pull requests merged in 2023-10, with the labels that each got.

#981 export GenerateSarifContentFromResults function
  xray/utils/resultwriter.go
Labels: ignore for release

#976 Build flat dependency trees while auditing Gradle projects
  buildscripts/download-jars.sh
  xray/commands/audit/sca/java/gradle-dep-tree.jar
  xray/commands/audit/sca/java/gradle.go
  xray/commands/audit/sca/java/gradle_test.go
  xray/commands/audit/sca/java/javautils.go
  xray/commands/audit/sca/java/javautils_test.go
Labels: improvement

#974 Transfer - Additional logs
  artifactory/commands/transferfiles/delayedartifactshandler.go
  artifactory/commands/transferfiles/errorshandler.go
  artifactory/commands/transferfiles/manager.go
Labels: ignore for release

#973 Transfer - Fix handling delayed files condition
  artifactory/commands/transferfiles/delayedartifactshandler.go
Labels: bug

#968 Fix Sarif output driver issues and Xray Sca locations
  utils/coreutils/techutils.go
  xray/commands/audit/jas/applicability/applicabilitymanager.go
  xray/commands/audit/jas/applicability/applicabilitymanager_test.go
  xray/commands/audit/jas/common.go
  xray/commands/audit/jas/commons_test.go
  xray/commands/audit/jas/iac/iacscanner.go
  xray/commands/audit/jas/iac/iacscanner_test.go
  xray/commands/audit/jas/sast/sastscanner.go
  xray/commands/audit/jas/sast/sastscanner_test.go
  xray/commands/audit/jas/secrets/secretsscanner.go
  xray/commands/audit/jas/secrets/secretsscanner_test.go
  xray/commands/audit/jasrunner.go
  xray/utils/analyzermanager.go
  xray/utils/resultwriter.go
  xray/utils/resultwriter_test.go
  xray/utils/sarifutils.go
  xray/utils/sarifutils_test.go
  xray/utils/test_sarifutils.go
Labels: bug

#938 Support Platform Access Token
  general/envsetup/envsetup.go
  general/token/accesstokencreate.go
  go.mod
  go.sum
Labels: new feature

#951 Support curation npm tree calc by package-lock only
  go.mod
  go.sum
  xray/commands/audit/sca/java/javautils.go
  xray/commands/audit/sca/npm/npm.go
  xray/commands/audit/sca/npm/npm_test.go
  xray/commands/audit/scarunner.go
  xray/commands/curation/curationaudit.go
  xray/utils/auditbasicparams.go
  xray/utils/auditnpmparams.go
Labels: improvement

#983 Transfer - Add 1 minute timeout to all requests
  artifactory/commands/transferfiles/longpropertycheck.go
  artifactory/commands/transferfiles/utils.go
  artifactory/utils/storageinfo.go
  artifactory/utils/utils.go
  go.mod
  go.sum
Labels: improvement

#985 Updating dependencies
  go.mod
  go.sum
Labels: ignore for release

#986 Upgrade jfrog-cli-core to 2.44.1
  go.mod
  go.sum
Labels: ignore for release

#975 Docker scan - map vulnerabilities to Dockerfile commands
  go.mod
  go.sum
  xray/commands/scan/buildscan.go
  xray/commands/scan/dockerscan.go
  xray/commands/scan/scan.go
  xray/formats/conversion.go
  xray/formats/table.go
  xray/utils/resultstable.go
  xray/utils/resultstable_test.go
  xray/utils/resultwriter.go
Labels: new feature

#989 Upgrade JFrog-CLI-Core to v.2.45.0
  go.mod
  go.sum
Labels: ignore for release

#990 Revert "Docker scan - map vulnerabilities to Dockerfile commands (#975)"
  go.mod
  go.sum
  xray/commands/scan/buildscan.go
  xray/commands/scan/dockerscan.go
  xray/commands/scan/scan.go
  xray/formats/conversion.go
  xray/formats/table.go
  xray/utils/resultstable.go
  xray/utils/resultstable_test.go
  xray/utils/resultwriter.go
Labels: bug

#991 Transfer - Improve the graceful stop mechanism
  artifactory/commands/transferfiles/phase.go
  go.mod
  go.sum
Labels: improvement

#980 Transfer - Show delayed files
  .github/workflows/analysis.yml
  artifactory/commands/transferfiles/delayedartifactshandler.go
  artifactory/commands/transferfiles/state/runstatus.go
  artifactory/commands/transferfiles/state/statemanager.go
  artifactory/commands/transferfiles/status.go
  artifactory/commands/transferfiles/status_test.go
  artifactory/commands/transferfiles/transfer.go
  artifactory/commands/transferfiles/transferfileprogress.go
  utils/progressbar/progressbarmng.go
  utils/progressbar/transferprogressbarmanager.go
Labels: improvement

#995 Transfer - Show visited folders counter
  artifactory/commands/transferfiles/delayedartifactshandler.go
  artifactory/commands/transferfiles/fulltransfer.go
  artifactory/commands/transferfiles/state/runstatus.go
  artifactory/commands/transferfiles/state/statemanager.go
  artifactory/commands/transferfiles/state/statemanager_test.go
  artifactory/commands/transferfiles/status.go
  artifactory/commands/transferfiles/status_test.go
  artifactory/commands/transferfiles/transfer.go
  artifactory/commands/transferfiles/transferfileprogress.go
  utils/progressbar/transferprogressbarmanager.go
Labels: improvement

#997 Transfer - Fix some issues in the progressbar
  utils/progressbar/progressbarmng.go
  utils/progressbar/transferprogressbarmanager.go
Labels: bug

#998 Update dependencies
  go.mod
  go.sum
Labels: ignore for release

#999 Transfer - Fix phase 3 progressbar
  artifactory/commands/transferfiles/delayedartifactshandler.go
  artifactory/commands/transferfiles/delayedartifactshandler_test.go
  artifactory/commands/transferfiles/fileserror.go
  artifactory/commands/transferfiles/status.go
  artifactory/commands/transferfiles/status_test.go
  utils/progressbar/transferprogressbarmanager.go
Labels: bug

#1000 Transfer - Progress should only represent successful storage transfer
  utils/progressbar/progressbarmng.go
  utils/progressbar/transferprogressbarmanager.go
Labels: bug

#1003 Transfer - Fix "close of closed channel" panic
  artifactory/commands/transferfiles/delayedartifactshandler.go
Labels: bug

#1002 Support running npm install without package.json
  artifactory/commands/npm/publish.go
  go.mod
  go.sum
  xray/commands/audit/sca/npm/npm.go
  xray/commands/audit/sca/yarn/yarn.go
Labels: improvement

#1004 Transfer - Remove recursive locks in snapshot node
  utils/reposnapshot/node.go
Labels: bug

#1005 Transfer - Graceful stop does not stop immediately
  artifactory/commands/transferfiles/manager.go
  artifactory/commands/transferfiles/phase.go
  artifactory/commands/transferfiles/phase_test.go
  artifactory/commands/transferfiles/utils.go
Labels: bug

#1006 Fix poetry tests on Windows
  .github/workflows/test.yml
  xray/commands/audit/sca/python/python_test.go
  xray/commands/testdata/poetry-project/poetry.lock
  xray/commands/testdata/poetry-project/pyproject.toml
Labels: ignore for release

#1008 Transfer - Increase locally generated concurrency
  artifactory/commands/transferfiles/localgeneratedfilter.go
Labels: improvement

#1009 Upgrade jfrog-cli-core to 2.45.4
  go.mod
  go.sum
Labels: ignore for release

#1011 Enhancements to Artifactory Integration and NPM dependency tree building
  artifactory/utils/projectconfig.go
  go.mod
  go.sum
  xray/commands/audit/auditparams.go
  xray/commands/audit/sca/npm/npm.go
  xray/commands/audit/sca/npm/npm_test.go
  xray/commands/audit/scarunner.go
  xray/utils/auditbasicparams.go
Labels: improvement

#1010 Transfer - Interruption may causes data loss
  artifactory/commands/transferfiles/delayedartifactshandler.go
  artifactory/commands/transferfiles/fileserror.go
  artifactory/commands/transferfiles/utils.go
Labels: bug
