Repository jfrog/jfrog-cli-core, pull requests merged in 2023-02, with the labels that each got.

#688 Fix static analysis and formatting
  artifactory/commands/golang/archive.go
  artifactory/commands/transferinstall/datatransferinstall_test.go
  artifactory/commands/utils/questionnaire.go
  distribution/commands/deletebundle.go
  utils/coreutils/tableutils.go
  utils/lock/lock_test.go
  xray/commands/audit/generic/auditmanager.go
Labels: ignore for release

#685 Change the log level while searching for the build name
  artifactory/utils/buildutils.go
Labels: improvement

#691 Unexpected error when there are no deployable artifacts
  artifactory/commands/utils/result.go
Labels: bug

#693 Improve Xray indexer download error handling and update dependencies
  go.mod
  go.sum
  xray/audit/java/mvn_test.go
  xray/commands/offlineupdate/offlineupdate.go
  xray/commands/testdata/maven-example/multi1/pom.xml
  xray/commands/testdata/maven-example/pom.xml
  xray/utils/downloadindexer.go
Labels: improvement

#695 Fix node v18+ .nprmc private registry E401 issue
  artifactory/commands/npm/common.go
  artifactory/commands/npm/installorci.go
  artifactory/commands/npm/installorci_test.go
  go.mod
Labels: bug

#686 Add Advanced Security to Xray's offline DB sync
  xray/commands/offlineupdate/offlineupdate.go
  xray/commands/offlineupdate/offlineupdate_test.go
Labels: new feature
