Repository jfrog/jfrog-cli-core, pull requests merged in 2023-04, with the labels that each got.

#706 Improve UI for scan command
  xray/commands/audit/generic/generic.go
  xray/commands/scan/buildscan.go
  xray/commands/scan/scan.go
  xray/formats/conversion.go
  xray/formats/table.go
  xray/utils/resultstable.go
  xray/utils/resultstable_test.go
  xray/utils/resultwriter.go
Labels: improvement

#732 Upgrade go version in go.mod to 1.20
  .github/workflows/analysis.yml
  .github/workflows/frogbot-scan-and-fix.yml
  .github/workflows/frogbot-scan-pr.yml
  .github/workflows/test.yml
  go.mod
Labels: improvement

#733 Fix lint issues found
  artifactory/commands/buildinfo/addgit.go
  artifactory/commands/generic/download.go
  artifactory/commands/golang/archive.go
  artifactory/commands/utils/remoteurlchecker.go
  go.mod
  go.sum
  plugins/components/conversionlayer.go
  xray/audit/java/gradle.go
  xray/audit/java/javautils.go
  xray/audit/java/mvn.go
Labels: improvement

#721 Config transfer - ensure target not older than source
  artifactory/commands/utils/transferconfigbase.go
  artifactory/commands/utils/transferconfigbase_test.go
Labels: improvement

#736 Flatten audit graph
  go.mod
  go.sum
  xray/audit/commonutils.go
  xray/audit/commonutils_test.go
  xray/commands/audit/generic/auditmanager.go
Labels: improvement

#719 Use gradle-dep-tree with Audit
  artifactory/commands/gradle/gradle.go
  artifactory/utils/buildinfoproperties.go
  utils/config/config.go
  utils/coreutils/techutils.go
  utils/mvn/utils.go
  xray/audit/java/gradle.go
  xray/audit/java/gradle_test.go
  xray/audit/java/javautils.go
  xray/commands/audit/generic/auditmanager.go
  xray/commands/testdata/gradle-example-ci-server/build.gradle
Labels: improvement

#737 Include sha2 field in jf rt search results
  artifactory/utils/search.go
Labels: improvement

#744 Fix Gradle audit access token handling
  artifactory/commands/transferfiles/delayedartifactshandler.go
  artifactory/commands/transferfiles/errorshandler.go
  xray/audit/java/gradle.go
Labels: bug

#742 Disable Enforcer and Checkstyle in Maven audit
  xray/audit/java/mvn.go
Labels: improvement

#746 Add ignore-scripts flag to npm audit
  xray/audit/npm/npm.go
  xray/audit/npm/npm_test.go
  xray/commands/testdata/npm-scripts/package.json
Labels: improvement

#745 Added the Frogbot badge to the README
  README.md
Labels: improvement

#747 Fix wrong audit logs following the Flatten Graph change
  artifactory/utils/buildinfoproperties.go
  go.mod
  go.sum
  xray/audit/commonutils.go
  xray/commands/audit/generic/auditmanager.go
  xray/commands/scan/scan.go
Labels: bug

#748 Make Xray version validation to run only once on multi project Audit
  xray/audit/commonutils.go
  xray/commands/audit/generic/auditmanager.go
Labels: improvement

#749 Fix GoSec static analysis action
  .github/workflows/analysis.yml
Labels: ignore for release

#750 Audit - Log the list of flattened dependencies in debug
  artifactory/commands/transferfiles/fulltransfer.go
  artifactory/commands/transferfiles/transferfileprogress.go
  go.mod
  go.sum
  pipelines/commands/status.go
  pipelines/commands/version.go
  utils/lock/utils_unix.go
  utils/progressbar/transferprogressbarmanager.go
  xray/audit/java/gradle.go
  xray/commands/audit/generic/auditmanager.go
Labels: improvement

#740 Add compatibility to include reference tokens
  go.mod
  go.sum
  utils/config/tokenrefresh.go
Labels: ignore for release

#754 Upgrade jfrog-cli-core to 2.31.2
  go.mod
  go.sum
Labels: ignore for release

#755 Simplify assignment in removeFederatedMembers
  artifactory/commands/utils/transferconfigbase.go
Labels: ignore for release

#741 Improve unarchive inspection
  artifactory/commands/generic/download.go
  artifactory/utils/dependenciesutils.go
  common/spec/builder.go
  common/spec/specfiles.go
  go.mod
  go.sum
  xray/commands/offlineupdate/offlineupdate.go
  xray/utils/downloadindexer.go
Labels: improvement

#758 Add Frogbot scan daily schedule and remove frogbot-config.yml
  .frogbot/frogbot-config.yml
  .github/workflows/frogbot-scan-and-fix.yml
Labels: improvement

#757 Support SERVER_ID environment variable
  utils/coreutils/coreconsts.go
Labels: improvement
