Repository jfrog/jfrog-cli-core, pull requests merged in 2023-08, with the labels that each got.

#883 Use XrayID in the SimplifyVulnerabilities/SimplifyViolations key
  go.mod
  go.sum
  xray/utils/resultstable.go
  xray/utils/resultstable_test.go
Labels: bug

#885 Remove deprecated pkg/errors
  artifactory/commands/transferinstall/datatransferinstall.go
  artifactory/commands/utils/checkrunner_test.go
  go.mod
  go.sum
  utils/coreutils/utils.go
Labels: ignore for release

#878 Yarn V1 Audit
  go.mod
  go.sum
  xray/audit/yarn/yarn.go
Labels: new feature

#887 Upgrade jfrog-client-go & build-info-go
  go.mod
  go.sum
Labels: ignore for release

#890 Fix duplicate rows and added scope for component name
  xray/commands/curation/audit.go
  xray/commands/curation/audit_test.go
Labels: bug

#892 Updating techutils
  utils/coreutils/techutils.go
Labels: ignore for release

#895 Set relative file path for secrets & add secrets suppression
  xray/audit/jas/iacscanner.go
  xray/audit/jas/iacscanner_test.go
  xray/audit/jas/jasmanager.go
  xray/audit/jas/secretsscanner.go
  xray/audit/jas/secretsscanner_test.go
  xray/commands/testdata/secrets-scan/contain-secrets-multi-wd.sarif
  xray/commands/testdata/secrets-scan/contain-secrets.sarif
  xray/commands/testdata/secrets-scan/no-secrets.sarif
Labels: improvement

#900 Fix npm output and some syntax issues
  .github/workflows/test.yml
  artifactory/commands/buildinfo/publish_test.go
  artifactory/commands/npm/npmcommand.go
  artifactory/commands/transfer/settings.go
  artifactory/commands/yarn/yarn.go
  artifactory/utils/container/buildinfo_test.go
  general/envsetup/envsetup.go
  go.mod
  go.sum
  utils/config/tokenrefresh.go
  utils/coreutils/coreconsts.go
  utils/coreutils/utils.go
  xray/commands/curation/audit.go
  xray/commands/utils/utils_test.go
  xray/utils/resultwriter_test.go
Labels: bug

#894 Refactor advanced security scanners
  xray/audit/jas/applicabilitymanager.go
  xray/audit/jas/applicabilitymanager_test.go
  xray/audit/jas/iacscanner.go
  xray/audit/jas/iacscanner_test.go
  xray/audit/jas/jasmanager.go
  xray/audit/jas/jasmanager_test.go
  xray/audit/jas/secretsscanner.go
  xray/audit/jas/secretsscanner_test.go
  xray/commands/audit/generic/auditmanager.go
  xray/utils/analyzermanager.go
  xray/utils/resultwriter.go
Labels: ignore for release

#902 Add progress bar to JFrog Advanced Security scanners
  artifactory/utils/container/buildinfo_test.go
  xray/audit/jas/applicabilitymanager_test.go
  xray/audit/jas/jasmanager.go
  xray/audit/jas/jasmanager_test.go
  xray/commands/audit/generic/auditmanager.go
  xray/utils/models.go
Labels: improvement

#904 Web login and config improvements
  artifactory/utils/weblogin.go
  common/commands/config.go
  general/login/login.go
Labels: ignore for release

#906 Transfer config - Issue in repos assigned to projects
  artifactory/commands/transferconfig/transferconfig.go
  artifactory/commands/transferconfig/transferconfig_test.go
  artifactory/commands/transferconfigmerge/transferconfigmerge.go
  artifactory/commands/utils/transferconfigbase.go
  artifactory/commands/utils/transferconfigbase_test.go
  common/tests/utils.go
Labels: bug

#909 Improve SCA and Advanced Security error results
  xray/audit/commonutils.go
  xray/commands/audit/generic/auditmanager.go
  xray/commands/audit/generic/generic.go
  xray/utils/resultstable.go
  xray/utils/resultwriter.go
Labels: improvement

#913 Promote to v2.41.0
  go.mod
  go.sum
Labels: ignore for release

#910 Improve Audit command technology detection
  utils/coreutils/techutils.go
  xray/commands/audit/generic/auditmanager.go
  xray/commands/utils/utils.go
Labels: improvement

#911 Improve Audit table results view
  utils/coreutils/cmdutils.go
  utils/coreutils/tableutils.go
  xray/utils/resultstable.go
  xray/utils/resultwriter.go
Labels: improvement

#915 Fix non-interactive config without providing server ID
  common/commands/config.go
  common/commands/config_test.go
Labels: bug

#914 Improve Web Login Logs
  artifactory/utils/weblogin.go
Labels: improvement

#912 Fix Python Contextual analysis missing dependencies issue
  xray/audit/jas/applicabilitymanager.go
  xray/audit/jas/applicabilitymanager_test.go
  xray/audit/jas/jasmanager.go
  xray/audit/jas/jasmanager_test.go
  xray/commands/audit/generic/auditmanager.go
  xray/commands/audit/generic/auditmanager_test.go
  xray/commands/curation/audit.go
  xray/utils/models.go
Labels: bug

#897 Transfer plugin install - Trim the input JFrog home path
  artifactory/commands/transferinstall/datatransferinstall.go
Labels: improvement

#916 Revert Anaylzer manager version
  xray/commands/utils/utils.go
  xray/utils/analyzermanager.go
Labels: ignore for release

#901 Use Gradle extractor 5 on Gradle >= 6.8.1
  artifactory/utils/gradleinitscript.go
  go.mod
  go.sum
  utils/gradle/utils.go
Labels: improvement

#920 update build-info-go dependency
  go.mod
  go.sum
Labels: improvement

#859 Support Lifecycle Release Bundle Distribute
  common/spec/distributionrules.go
  distribution/commands/deletebundle.go
  distribution/commands/distributebundle.go
  go.mod
  go.sum
  lifecycle/common.go
  lifecycle/createcommon.go
  lifecycle/createfrombuilds.go
  lifecycle/createfrombundles.go
  lifecycle/distribute.go
  lifecycle/promote.go
Labels: new feature

#903 Techutils update - Adding fields for fix command in NuGet
  utils/coreutils/techutils.go
Labels: ignore for release

#921 Fix severity level mapping
  xray/commands/utils/utils_test.go
  xray/utils/analyzermanager.go
  xray/utils/analyzermanager_test.go
  xray/utils/resultstable.go
  xray/utils/resultwriter.go
Labels: bug
