Repository jfrog/jfrog-cli-core, pull requests merged in 2023-05, with the labels that each got.

#729 Config transfer - support checking remote repos in Artifactory >= 7.49
  artifactory/commands/transferconfig/transferconfig.go
  artifactory/commands/utils/remoteurlchecker.go
  artifactory/commands/utils/remoteurlchecker_test.go
  artifactory/commands/utils/testdata/remoteurlchecker/nuget_repo.json
  go.mod
  go.sum
Labels: improvement

#760 Support for a new JFROG_CLI_RELEASES_REPO environment variable
  artifactory/utils/dependenciesutils.go
  artifactory/utils/dependenciesutils_test.go
  utils/coreutils/utils.go
  utils/coreutils/utils_test.go
  xray/audit/java/gradle.go
  xray/audit/java/gradle_test.go
  xray/commands/audit/generic/generic.go
Labels: improvement

#761 Support JFROG_CLI_SERVER_ID environment variable as fallback server-id-resolve/deploy
  artifactory/commands/utils/configfile.go
  artifactory/commands/utils/configfile_test.go
Labels: improvement

#766 Update test.yml
  .github/workflows/test.yml
Labels: ignore for release

#764 Add filter flags for Audit & Scan commands
  go.mod
  go.sum
  xray/audit/commonutils.go
  xray/commands/audit/generic/auditmanager.go
  xray/commands/audit/generic/generic.go
  xray/commands/scan/scan.go
  xray/commands/utils.go
  xray/commands/utils_test.go
  xray/utils/resultstable.go
Labels: new feature

#767 Fix Request Parameters Issue for Scan command
  xray/commands/scan/scan.go
  xray/utils/resultstable.go
  xray/utils/resultstable_test.go
Labels: bug

#770 Fix wrong threads flag extracting for docker commands
  utils/coreutils/cmdutils.go
Labels: bug

#753 CVE applicability indication for `jf audit`
  utils/coreutils/tableutils.go
  utils/coreutils/tableutils_test.go
  xray/commands/audit/applicabilitymanager.go
  xray/commands/audit/applicabilitymanager_test.go
  xray/commands/audit/generic/generic.go
  xray/commands/scan/buildscan.go
  xray/commands/scan/scan.go
  xray/commands/testdata/applicability-scan/applicable-cve-results.sarif
  xray/commands/testdata/applicability-scan/empty-results.sarif
  xray/commands/testdata/applicability-scan/no-applicable-cves-results.sarif
  xray/commands/utils.go
  xray/formats/conversion.go
  xray/formats/simplejsonapi.go
  xray/formats/table.go
  xray/utils/analyzermanager.go
  xray/utils/analyzermanager_test.go
  xray/utils/resultstable.go
  xray/utils/resultstable_test.go
  xray/utils/resultwriter.go
  xray/utils/resultwriter_test.go
Labels: new feature

#756 New curation-audit command
  artifactory/commands/npm/npmcommand.go
  artifactory/commands/utils/conditionaluploadutils.go
  go.mod
  go.sum
  utils/tests/utils.go
  xray/audit/commonutils.go
  xray/audit/commonutils_test.go
  xray/audit/go/golang.go
  xray/audit/java/gradle.go
  xray/audit/java/javautils.go
  xray/audit/java/mvn.go
  xray/audit/npm/npm.go
  xray/audit/npm/npm_test.go
  xray/audit/nuget/nuget.go
  xray/audit/nuget/nuget_test.go
  xray/audit/python/python.go
  xray/audit/yarn/yarn.go
  xray/audit/yarn/yarn_test.go
  xray/commands/audit/applicabilitymanager.go
  xray/commands/audit/applicabilitymanager_test.go
  xray/commands/audit/generic/auditmanager.go
  xray/commands/audit/generic/generic.go
  xray/commands/curation/audit.go
  xray/commands/curation/audit_test.go
  xray/commands/scan/buildscan.go
  xray/commands/scan/dockerscan.go
  xray/commands/scan/scan.go
  xray/commands/testdata/npm-project/.jfrog/projects/npm.yaml
  xray/commands/testdata/npm-project/package-lock.json
  xray/commands/testdata/npm-project/package.json
  xray/commands/utils/utils.go
  xray/commands/utils/utils_test.go
  xray/utils/models.go
  xray/utils/resultwriter.go
Labels: ignore for release

#776 Upgrade jfrog-client-go & build-info-go
  go.mod
  go.sum
Labels: ignore for release

#769 Wrap Unauthorized 401 when downloading Xray indexer with informative error
  xray/utils/downloadindexer.go
Labels: improvement

#778 Audit - Fix missing params.dependencyTrees field
  xray/commands/audit/generic/auditmanager.go
Labels: bug

#772 Add SetOutputWriter for MvnUtils
  artifactory/commands/mvn/mvn.go
  go.mod
  go.sum
  utils/mvn/utils.go
  xray/audit/java/mvn.go
  xray/commands/audit/generic/auditmanager.go
Labels: improvement

#781 Fix Cves NPE
  xray/utils/resultstable.go
Labels: bug

#782 Upgrade jfrog-cli-core to 2.33.2
  go.mod
  go.sum
Labels: ignore for release

#768 Fix Maven conditional upload, add err if deployer not set
  artifactory/commands/gradle/gradle.go
  artifactory/commands/mvn/mvn.go
  utils/mvn/utils.go
Labels: bug

#735 Move the npm install execution to build-info-go
  artifactory/commands/npm/common.go
  artifactory/commands/npm/generic.go
  artifactory/commands/npm/installorci.go
  artifactory/commands/npm/npmcommand.go
  artifactory/commands/npm/npmcommand_test.go
  artifactory/commands/npm/publish.go
  go.mod
  go.sum
Labels: improvement

#771 Fix Npm dependency graph building & avoid duplicating paths if there is a direct one
  xray/audit/commonutils.go
  xray/audit/commonutils_test.go
  xray/audit/npm/npm.go
  xray/audit/npm/npm_test.go
  xray/commands/testdata/npm/dependencies.json
Labels: bug

#789 Transfer config - change export dir permissions
  artifactory/commands/transferconfig/transferconfig.go
Labels: improvement

#787 Audit - fix wrong direct dependency and params restructure
  artifactory/commands/npm/npmcommand.go
  xray/audit/commonutils.go
  xray/commands/audit/generic/auditmanager.go
  xray/commands/audit/generic/generic.go
  xray/commands/curation/audit.go
  xray/utils/models.go
Labels: bug

#785 Transfer Config Merge - avoid Artifactory min version check
  artifactory/commands/transferconfig/transferconfig.go
  artifactory/commands/transferconfig/transferconfig_test.go
  artifactory/commands/transferconfigmerge/transferconfigmerge.go
  artifactory/commands/utils/transferconfigbase.go
  artifactory/commands/utils/transferconfigbase_test.go
Labels: improvement

#790 Avoid running tests and static analysis on tags
  .github/workflows/analysis.yml
  .github/workflows/test.yml
Labels: ignore for release

#792 Avoid running tests and static analysis on tags
  .github/workflows/analysis.yml
  .github/workflows/frogbot-scan-and-fix.yml
  .github/workflows/test.yml
Labels: ignore for release

#791 Update build-info-go
  go.mod
  go.sum
Labels: ignore for release

#779 Fix curation flaky tests
  xray/commands/curation/audit_test.go
Labels: ignore for release

#793 Transfer Config Merge - Fix filter keys issue and add additional filter keys
  artifactory/commands/transferconfigmerge/transferconfigmerge.go
Labels: bug

#794 Audit JSON update to retrieve only Xray results
  xray/utils/resultwriter.go
Labels: ignore for release

#786 Improve JFrog's dependencies download
  artifactory/utils/dependenciesutils.go
  artifactory/utils/dependenciesutils_test.go
  go.mod
  go.sum
  utils/coreutils/utils.go
  utils/coreutils/utils_test.go
  utils/gradle/utils.go
  utils/mvn/utils.go
  xray/commands/audit/applicabilitymanager.go
  xray/commands/audit/applicabilitymanager_test.go
  xray/commands/audit/generic/auditmanager.go
  xray/commands/audit/generic/generic.go
  xray/utils/analyzermanager.go
  xray/utils/downloadindexer.go
Labels: improvement

#799 Transfer config - insufficient export dir permissions
  artifactory/commands/transferconfig/transferconfig.go
Labels: bug

#800 Handle empty response from GetRemoteFileDetails
  artifactory/commands/buildinfo/buildappend.go
  artifactory/utils/dependenciesutils.go
  go.mod
  go.sum
Labels: bug

#802 Adjust `Contextual Analysis` run conditions message
  xray/commands/audit/generic/generic.go
  xray/utils/resultwriter.go
Labels: improvement

#803 Missing auth details while downloading an extractor
  artifactory/utils/dependenciesutils.go
  artifactory/utils/dependenciesutils_test.go
Labels: bug

#797 Update Frogbot GitHub action
  .github/workflows/frogbot-scan-and-fix.yml
Labels: ignore for release

#805 Make the "DownloadDependency" utility public
  artifactory/utils/dependenciesutils.go
Labels: ignore for release

#808 Infinite loop while parsing Npm dependency list
  xray/audit/npm/npm.go
Labels: bug

#809 Fix Npm parse tree test
  xray/audit/npm/npm_test.go
Labels: ignore for release

#810 Contextual Analysis Column appearance update
  xray/commands/audit/applicabilitymanager.go
  xray/commands/audit/applicabilitymanager_test.go
Labels: improvement

#813 Scanning scoped Yarn projects failed
  xray/audit/yarn/yarn.go
  xray/audit/yarn/yarn_test.go
Labels: bug

#812 Transfer - exit on unrecoverable errors
  artifactory/commands/transferfiles/transfer.go
Labels: bug

#814 Fix `Jf Audit` command entitlements service error
  xray/commands/audit/generic/auditmanager.go
  xray/commands/audit/generic/generic.go
  xray/utils/analyzermanager.go
Labels: bug
