Repository jfrog/jfrog-cli-core, pull requests merged in 2023-09, with the labels that each got.

#919 Add SAST advance scan
  xray/audit/jas/applicabilitymanager.go
  xray/audit/jas/applicabilitymanager_test.go
  xray/audit/jas/iacscanner.go
  xray/audit/jas/iacscanner_test.go
  xray/audit/jas/jasmanager.go
  xray/audit/jas/jasmanager_test.go
  xray/audit/jas/sastscanner.go
  xray/audit/jas/sastscanner_test.go
  xray/audit/jas/secretsscanner.go
  xray/audit/jas/secretsscanner_test.go
  xray/commands/audit/generic/generic.go
  xray/commands/testdata/sast-scan/contains-sast-violations.sarif
  xray/commands/testdata/sast-scan/no-violations.sarif
  xray/formats/conversion.go
  xray/formats/simplejsonapi.go
  xray/formats/table.go
  xray/utils/analyzermanager.go
  xray/utils/analyzermanager_test.go
  xray/utils/resultstable.go
  xray/utils/resultwriter.go
  xray/utils/resultwriter_test.go
  xray/utils/sarifutils.go
Labels: new feature

#922 Fix sarif convert
  xray/audit/jas/jasmanager.go
  xray/utils/analyzermanager.go
  xray/utils/resultstable.go
  xray/utils/sarifutils.go
Labels: ignore for release

#930 Restructure Xray code
  utils/coreutils/techutils.go
  utils/usage/usage.go
  xray/commands/audit/audit.go
  xray/commands/audit/sca/common.go
  xray/commands/audit/scarunner.go
  xray/commands/curation/curationaudit.go
  xray/commands/curation/curationaudit_test.go
  xray/commands/scan/buildscan.go
  xray/commands/scan/dockerscan.go
  xray/commands/scan/scan.go
  xray/commands/utils/utils.go
  xray/scangraph/params.go
  xray/scangraph/scangraph.go
  xray/scangraph/scangraph_test.go
  xray/utils/xraymanager.go
Labels: ignore for release

#933 Rename Audit structs
  utils/coreutils/utils.go
  utils/coreutils/utils_test.go
  xray/commands/audit/audit.go
  xray/commands/audit/auditparams.go
  xray/commands/audit/jas/common.go
  xray/commands/audit/sca/java/javautils.go
  xray/commands/audit/scarunner.go
  xray/commands/curation/curationaudit.go
  xray/utils/analyzermanager.go
  xray/utils/analyzermanager_test.go
  xray/utils/auditbasicparams.go
  xray/utils/models.go
Labels: ignore for release

#934 Fix excluding locally generated refresh tokens
  utils/config/config.go
Labels: bug

#935 Set analyzer manager version by environment variable
  xray/commands/audit/jasrunner.go
  xray/utils/analyzermanager.go
  xray/utils/resultwriter.go
Labels: improvement

#936 Improve audit data handling
  xray/commands/audit/audit.go
  xray/commands/audit/jas/applicability/applicabilitymanager.go
  xray/commands/audit/jas/applicability/applicabilitymanager_test.go
  xray/commands/audit/jas/common.go
  xray/commands/audit/jas/common_test.go
  xray/commands/audit/jas/iac/iacscanner.go
  xray/commands/audit/jas/iac/iacscanner_test.go
  xray/commands/audit/jas/sast/sastscanner.go
  xray/commands/audit/jas/sast/sastscanner_test.go
  xray/commands/audit/jas/secrets/secretsscanner.go
  xray/commands/audit/jas/secrets/secretsscanner_test.go
  xray/commands/audit/jasrunner.go
  xray/commands/testdata/applicability-scan/applicable-cve-results.sarif
  xray/commands/testdata/applicability-scan/no-applicable-cves-results.sarif
  xray/formats/conversion.go
  xray/formats/simplejsonapi.go
  xray/utils/analyzermanager.go
  xray/utils/analyzermanager_test.go
  xray/utils/resultstable.go
  xray/utils/resultstable_test.go
  xray/utils/resultwriter.go
  xray/utils/resultwriter_test.go
  xray/utils/sarifutils.go
  xray/utils/sarifutils_test.go
Labels: improvement

#940 Add Xray Source Control Service
  go.mod
  go.sum
  xray/commands/audit/audit.go
  xray/commands/audit/jas/common.go
  xray/commands/audit/jasrunner.go
  xray/commands/audit/jasrunner_test.go
  xray/commands/audit/sca/common.go
  xray/scangraph/scangraph.go
  xray/utils/analyzermanager.go
Labels: improvement

#947 Unite relative path conversion
  xray/formats/conversion.go
  xray/formats/simplejsonapi.go
  xray/formats/table.go
  xray/utils/analyzermanager.go
  xray/utils/resultstable.go
  xray/utils/resultwriter.go
  xray/utils/sarifutils.go
Labels: ignore for release

#924 Mark usage source in logs
  utils/usage/usage.go
Labels: ignore for release

#948 Improve Golang audit logs
  xray/commands/audit/sca/go/golang.go
  xray/commands/audit/scarunner.go
  xray/utils/analyzermanager_test.go
  xray/utils/sarifutils.go
Labels: improvement

#952 Fix panic in Analyzer Manager execution
  xray/utils/analyzermanager.go
Labels: bug

#953 Don't send Xray usage until available for all users
  artifactory/utils/dependenciesutils.go
  utils/usage/usage.go
  utils/usage/usage_test.go
Labels: bug

#954 Sast advance scan
  xray/utils/analyzermanager.go
Labels: new feature

#941 Third party dependencies contextual analysis for npm
  xray/commands/audit/audit.go
  xray/commands/audit/auditparams.go
  xray/commands/audit/jas/applicability/applicabilitymanager.go
  xray/commands/audit/jas/applicability/applicabilitymanager_test.go
  xray/commands/audit/jas/common.go
  xray/commands/audit/jasrunner.go
  xray/commands/audit/jasrunner_test.go
  xray/commands/audit/sca/npm/npm.go
  xray/commands/audit/sca/npm/npm_test.go
  xray/commands/audit/sca/yarn/yarn.go
  xray/commands/audit/sca/yarn/yarn_test.go
  xray/commands/audit/scarunner.go
  xray/utils/auditbasicparams.go
  xray/utils/resultstable.go
  xray/utils/resultstable_test.go
Labels: improvement

#958 Rename tokens refresh thresholds
  go.mod
  go.sum
  utils/config/tokenrefresh.go
Labels: ignore for release

#959 Update dependencies
  go.mod
  go.sum
Labels: ignore for release

#960 Change GetIssueIdentifier access
  xray/utils/resultwriter.go
  xray/utils/resultwriter_test.go
Labels: ignore for release

#956 Transfer files - Remove redundant lock in snapshot
  artifactory/commands/transferfiles/state/transfersnapshot.go
Labels: improvement

#963 Transfer - pom.xml files should also be delayed
  artifactory/commands/transferfiles/delayedartifactshandler.go
Labels: bug

#964 Update Analyzer manager (1.3.2.2006984) to fix Java Contextual analysis issues
  xray/utils/analyzermanager.go
Labels: bug

#967 Promote version to 2.43.1
  go.mod
  go.sum
Labels: ignore for release

#927 Audit - licenses and build impact paths refactor
  general/cisetup/jenkinsfiledslgenerator.go
  utils/coreutils/techutils.go
  xray/commands/audit/jas/applicability/applicabilitymanager_test.go
  xray/commands/audit/jas/common.go
  xray/commands/audit/sca/common.go
  xray/commands/audit/sca/common_test.go
  xray/commands/curation/curationaudit.go
  xray/commands/curation/curationaudit_test.go
  xray/formats/conversion.go
  xray/formats/simplejsonapi.go
  xray/formats/table.go
  xray/utils/analyzermanager.go
  xray/utils/resultstable.go
  xray/utils/resultstable_test.go
  xray/utils/resultwriter.go
Labels: improvement

#966 Transfer - Send chunks if they are bigger than GiB
  artifactory/commands/transferfiles/api/types.go
  artifactory/commands/transferfiles/api/types_test.go
  artifactory/commands/transferfiles/fulltransfer.go
  artifactory/commands/transferfiles/transfer.go
  artifactory/commands/transferfiles/utils.go
Labels: improvement

#970 Show findings in Sast
  xray/utils/resultstable.go
Labels: bug

#965 Add tests for audit
  xray/commands/audit/jas/common_test.go
  xray/commands/audit/jas/sast/sastscanner.go
  xray/commands/audit/jas/sast/sastscanner_test.go
  xray/commands/audit/jas/secrets/secretsscanner.go
  xray/utils/analyzermanager_test.go
  xray/utils/resultstable_test.go
  xray/utils/sarifutils.go
  xray/utils/sarifutils_test.go
Labels: ignore for release

#929 Refactor Resultwriter
  xray/commands/audit/audit.go
  xray/commands/scan/buildscan.go
  xray/commands/scan/scan.go
  xray/utils/resultstable.go
  xray/utils/resultstable_test.go
  xray/utils/resultwriter.go
Labels: ignore for release

#943 Support JFrog Apps Config file
  go.mod
  go.sum
  xray/commands/audit/jas/applicability/applicabilitymanager.go
  xray/commands/audit/jas/applicability/applicabilitymanager_test.go
  xray/commands/audit/jas/common.go
  xray/commands/audit/jas/commons_test.go
  xray/commands/audit/jas/iac/iacscanner.go
  xray/commands/audit/jas/iac/iacscanner_test.go
  xray/commands/audit/jas/sast/sastscanner.go
  xray/commands/audit/jas/sast/sastscanner_test.go
  xray/commands/audit/jas/secrets/secretsscanner.go
  xray/commands/audit/jas/secrets/secretsscanner_test.go
  xray/commands/audit/jas/testdata/.jfrog/jfrog-apps-config.yml
  xray/utils/analyzermanager.go
Labels: improvement

#979 Report Usage - Improve Errors Messages
  utils/usage/usage.go
  utils/usage/usage_test.go
Labels: ignore for release

#977 Improve npm logs and error handling
  artifactory/commands/golang/go.go
  artifactory/commands/npm/npmcommand.go
  artifactory/commands/transferconfig/transferconfig.go
  artifactory/commands/transferconfigmerge/transferconfigmerge_test.go
  artifactory/commands/utils/npmcmdutils.go
  artifactory/utils/dependenciesutils.go
  general/envsetup/envsetup.go
  general/invite/invite.go
  go.mod
  go.sum
  xray/commands/audit/scarunner.go
Labels: improvement
