Repository jfrog/jfrog-cli-core, pull requests merged in 2024-07, with the labels that each got.

#1198 Simplify the Artifactory Download Progress Bar
  common/progressbar/filesprogressbar.go
  go.mod
  go.sum
Labels: improvement

#1199 Fix terraform interactive config
  common/commands/configfile.go
Labels: bug

#1200 Update dependencies
  artifactory/commands/npm/npmcommand.go
  go.mod
  go.sum
Labels: ignore for release

#1205 Web login - Make the uuid bold in green
  artifactory/utils/weblogin.go
Labels: improvement

#1206 Upgrade jfrog-cli-core to 2.53.3
  go.mod
  go.sum
Labels: ignore for release

#1209 Upgrade depedencies
  go.mod
  go.sum
Labels: ignore for release

#1207 Fix progress bar race issue, and Improve UI
  artifactory/commands/container/buildcreate.go
  artifactory/commands/transferfiles/longpropertycheck.go
  artifactory/commands/transferfiles/transferfileprogress.go
  artifactory/commands/utils/precheckrunner/remoteurlchecker.go
  common/progressbar/filesprogressbar.go
  go.mod
  go.sum
  utils/progressbar/generalprogressbar.go
  utils/progressbar/progressbarmng.go
  utils/progressbar/taskswithheadlineprog.go
  utils/progressbar/transferprogressbarmanager.go
Labels: improvement

#1213 Improve progress spinner message
  .github/workflows/analysis.yml
  artifactory/commands/generic/download.go
  artifactory/commands/generic/upload.go
  artifactory/commands/npm/npmcommand_test.go
  artifactory/commands/transferfiles/transfer_test.go
  artifactory/utils/download.go
  common/commands/config_test.go
  common/progressbar/filesprogressbar.go
  go.mod
  go.sum
  lifecycle/export.go
  utils/config/configtoken_test.go
Labels: improvement

#1214 Add hidden option for namespace
  plugins/components/conversionlayer.go
  plugins/components/structure.go
Labels: improvement

#1204 Fix npm for groups access tokens
  artifactory/commands/npm/common.go
  artifactory/commands/npm/npmcommand.go
  artifactory/commands/npm/npmcommand_test.go
  artifactory/commands/utils/npmcmdutils.go
  artifactory/commands/utils/npmcmdutils_test.go
  artifactory/commands/yarn/yarn.go
  artifactory/commands/yarn/yarn_test.go
Labels: bug

#1211 Add repo field to docker build-info artifacts
  artifactory/commands/generic/download.go
  artifactory/utils/container/buildinfo.go
  artifactory/utils/download.go
  go.mod
  go.sum
  lifecycle/export.go
Labels: improvement

#1201 Fix root module name handling in build info collection
  artifactory/commands/golang/go.go
  artifactory/commands/golang/gopublish.go
  artifactory/commands/npm/npmcommand.go
  artifactory/commands/npm/publish.go
  artifactory/commands/python/poetry.go
  artifactory/commands/python/python.go
  common/build/buildutils.go
  common/build/buildutils_test.go
  go.mod
  go.sum
Labels: bug

#1210 Add OriginalRepo and Relative Path to Go Publish
  artifactory/commands/golang/publish.go
  go.mod
  go.sum
Labels: improvement

#1212 Add originalRepo to mvn commands build-info
  artifactory/commands/mvn/mvn.go
  artifactory/commands/mvn/mvn_test.go
  artifactory/commands/mvn/testdata/buildinfo_files/buildinfo1
  utils/mvn/utils.go
Labels: improvement

#1215 Add modules from published build info to command summary
  artifactory/commands/buildinfo/publish.go
  artifactory/commands/commandssummaries/buildinfosummary.go
  artifactory/commands/commandssummaries/buildinfosummary_test.go
  artifactory/commands/commandssummaries/testdata/modules.md
  artifactory/commands/commandssummaries/testdata/table.md
  artifactory/commands/commandssummaries/uploadsummary.go
  artifactory/commands/commandssummaries/uploadsummary_test.go
  artifactory/commands/commandssummaries/utils.go
  artifactory/commands/commandssummaries/utils_test.go
  artifactory/commands/generic/upload.go
  artifactory/utils/utils.go
  artifactory/utils/utils_test.go
Labels: new feature

#1216 Revert commit "Fix root module name handling in build info collection"
  artifactory/commands/golang/go.go
  artifactory/commands/golang/gopublish.go
  artifactory/commands/npm/npmcommand.go
  artifactory/commands/npm/publish.go
  artifactory/commands/python/poetry.go
  artifactory/commands/python/python.go
  common/build/buildutils.go
  common/build/buildutils_test.go
Labels: ignore for release

#1217 embedded plugin context - don't set flags if not exists
  plugins/components/conversionlayer.go
  plugins/components/conversionlayer_test.go
Labels: bug

#1218 Upgrade to 2.54.0
  go.mod
  go.sum
Labels: ignore for release
