Repository jfrog/jfrog-cli-core, pull requests merged in 2024-10, with the labels that each got.

#1277 Remove API Key suggestion from config command
  common/commands/config.go
  utils/ioutils/ioutils.go
Labels: improvement

#1273 Recursively search for the .mvn directpry
  go.mod
  go.sum
  utils/mvn/utils.go
Labels: bug

#1280 Improve get filtered repositories code
  artifactory/commands/transferfiles/transfer.go
  artifactory/utils/repositoryutils.go
  artifactory/utils/repositoryutils_test.go
  common/commands/configfile.go
Labels: ignore for release

#1281 Promote to v2.56.3
  go.mod
  go.sum
Labels: ignore for release

#1283 Upgrade jfrog-client-go to v1.47.3
  go.mod
  go.sum
Labels: improvement
