Repository jfrog/jfrog-cli-core, pull requests merged in 2024-03, with the labels that each got.

#1138 Curation - Recognize 403 or 500 errors from the tree builder
  utils/java/mvn.go
  utils/java/mvn_test.go
Labels: improvement

#1147 Update go.mod and go.sum
  go.mod
  go.sum
Labels: ignore for release

#1151 Fix poetry failing test
  utils/python/utils.go
Labels: ignore for release

#1152 Fix false positive ZipSlip when an archive starts with dot
  go.mod
  go.sum
Labels: bug

#1140 Artifactory Release Lifecycle Management - Support distribution sync and project
  go.mod
  go.sum
  lifecycle/common.go
  lifecycle/distribute.go
Labels: new feature

#1156 Fix npm publish test
  artifactory/commands/testdata/npm/npm-example-0.0.4.tgz
Labels: ignore for release

#1142 Artifactory Release Lifecycle Management - Support release bundle creation by aql and artifacts
  artifactory/commands/generic/search.go
  artifactory/utils/search.go
  go.mod
  go.sum
  lifecycle/createcommon.go
  lifecycle/createcommon_test.go
  lifecycle/createfromaql.go
  lifecycle/createfromartifacts.go
  lifecycle/createfrombuilds.go
  lifecycle/createfrombundles.go
Labels: new feature

#1129 Transfer - Consider the MIN_CHECKSUM_DEPLOY_SIZE_KB env var
  artifactory/commands/generic/upload.go
  artifactory/commands/transferfiles/api/types.go
  artifactory/commands/transferfiles/fulltransfer.go
  artifactory/commands/transferfiles/phase.go
  artifactory/commands/transferfiles/transfer.go
  artifactory/commands/transferfiles/utils.go
  artifactory/utils/upload.go
  go.mod
  go.sum
Labels: improvement

#1157 Promote version to 2.49.0
  go.mod
  go.sum
Labels: ignore for release

#1150 Additions to support Pnpm in frogbot
  utils/coreutils/techutils.go
Labels: ignore for release

#1158 Simplify file closer funcs
  .github/workflows/analysis.yml
  .github/workflows/test.yml
  artifactory/commands/generic/delete.go
  artifactory/commands/generic/upload.go
  artifactory/commands/golang/publish.go
  artifactory/commands/npm/publish.go
  artifactory/commands/python/dependencies/cache.go
  artifactory/commands/python/dependencies/dependencies.go
  artifactory/commands/terraform/terraformpublish.go
  artifactory/commands/transferfiles/errorshandler.go
  artifactory/commands/transferfiles/transfer.go
  artifactory/commands/utils/result_test.go
  artifactory/commands/utils/transfer.go
  artifactory/commands/utils/yarnutils.go
  artifactory/utils/container/buildinfo.go
  artifactory/utils/npm/config-list.go
  artifactory/utils/search.go
  artifactory/utils/transfersettings.go
  common/commands/config.go
  go.mod
  go.sum
  utils/config/encryption.go
  utils/config/tokenrefresh.go
  utils/coreutils/tableutils.go
  utils/plugins/utils.go
Labels: ignore for release

#1159 Update deprecated setup-go action and improve close funcs
  artifactory/commands/buildinfo/adddependencies.go
  artifactory/commands/dotnet/dotnetcommand.go
  artifactory/commands/generic/delete.go
  artifactory/commands/generic/download.go
  artifactory/commands/generic/upload.go
  artifactory/commands/golang/publish.go
  artifactory/commands/npm/publish.go
  artifactory/commands/python/poetry.go
  artifactory/commands/python/python.go
  artifactory/commands/terraform/terraformpublish.go
  artifactory/commands/transferconfig/transferconfig.go
  artifactory/commands/transferconfig/utils.go
  artifactory/commands/transferconfigmerge/transferconfigmerge.go
  artifactory/commands/transferfiles/delayedartifactshandler.go
  artifactory/commands/transferfiles/longpropertycheck.go
  artifactory/commands/utils/precheckrunner/checkrunner.go
  artifactory/utils/container/buildinfo.go
  artifactory/utils/utils.go
  common/build/buildutils.go
  common/progressbar/filesprogressbar.go
  go.mod
  go.sum
  utils/dependencies/utils.go
Labels: ignore for release

#1143 Artifactory Release Lifecycle Management - Add Export bundle function
  go.mod
  go.sum
  lifecycle/export.go
Labels: new feature

#1160 Use Gradle dep tree v3.0.2
  buildscripts/download-jars.sh
  utils/java/resources/gradle-dep-tree.jar
Labels: improvement

#1161 Remove Java Dep Tree content
  .github/workflows/embedded-jar-test.yml
  buildscripts/download-jars.sh
  utils/java/deptreemanager.go
  utils/java/deptreemanager_test.go
  utils/java/gradle.go
  utils/java/gradle_test.go
  utils/java/mvn.go
  utils/java/mvn_test.go
  utils/java/resources/gradle-dep-tree.jar
  utils/java/resources/maven-dep-tree.jar
  utils/java/resources/settings.xml
Labels: ignore for release

#1162 Fix npm publish with provided tarball
  artifactory/commands/npm/publish.go
  artifactory/commands/npm/publish_test.go
Labels: bug
