Repository jfrog/jfrog-cli-core, pull requests merged in 2024-05, with the labels that each got.

#1178 Update web login prompts
  artifactory/utils/weblogin.go
  common/commands/config.go
  general/login/login.go
Labels: improvement

#1168 Support npm distribution tags
  artifactory/commands/npm/npmcommand.go
  artifactory/commands/npm/publish.go
  utils/coreutils/cmdutils.go
Labels: improvement

#1177 Fix Refreshing Platform Access Tokens
  utils/config/tokenrefresh.go
Labels: bug

#1181 Add missing description on Xray help section subcommands
  plugins/components/conversionlayer.go
Labels: bug

#1184 Validate defered callback funcs are not nil before running
  artifactory/commands/dotnet/dotnetcommand.go
  artifactory/commands/transferfiles/transfer.go
  common/commands/config.go
  go.mod
  go.sum
Labels: bug

#1185 Update version to 2.52.0
  go.mod
  go.sum
Labels: ignore for release

#1180 move depTree logic from 'xrayutils.go' file
  utils/xray/xrayutils.go
Labels: ignore for release

#1179 Command Summaries
  artifactory/commands/buildinfo/publish.go
  artifactory/commands/commandssummaries/buildinfosummary.go
  artifactory/commands/commandssummaries/buildinfosummary_test.go
  artifactory/commands/commandssummaries/uploadsummary.go
  artifactory/commands/commandssummaries/uploadsummary_test.go
  artifactory/commands/generic/upload.go
  artifactory/utils/filetree.go
  artifactory/utils/filetree_test.go
  commandsummary/commandsummary.go
  commandsummary/commandsummary_test.go
  utils/coreutils/coreconsts.go
Labels: new feature

#1186 Update dependencies
  go.mod
  go.sum
Labels: ignore for release

#1188 Support evidence service
  artifactory/utils/utils.go
  go.mod
  go.sum
  utils/config/config.go
Labels: new feature
