Repository jfrog/jfrog-cli-core, pull requests merged in 2024-12, with the labels that each got.

#1307 Internal - Added the ability to add flag to existing context
  plugins/components/commandcomp.go
  utils/coreutils/coreconsts.go
Labels: improvement

#1310 Fix NuGet related tests
  .github/workflows/test.yml
Labels: ignore for release

#1308 Login command - Ensure JFrog Platform URL input is non-empty before proceeding
  general/login/login.go
  go.mod
  go.sum
Labels: improvement

#1314 Internal API - Visibility System support
  artifactory/commands/transferfiles/transfer.go
  artifactory/utils/utils.go
  common/commands/command.go
  go.mod
  go.sum
  utils/config/config.go
  utils/usage/usage.go
  utils/usage/visibility_system_manager.go
  utils/usage/visibility_system_manager_test.go
Labels: improvement

#1315 Internal API - Visibility System improvements
  go.mod
  go.sum
  utils/usage/visibility_system_manager.go
  utils/usage/visibility_system_manager_test.go
Labels: improvement

#1317 Internal API - New `product_version` field added to the Visibility Metric
  go.mod
  go.sum
  utils/usage/visibility_system_manager.go
  utils/usage/visibility_system_manager_test.go
Labels: improvement

#1316 Reduced the min npm version for supporting scoped auth
  artifactory/commands/npm/npmcommand.go
Labels: bug

#1318 Fix wrong replace in go.mod
  go.mod
  go.sum
Labels: ignore for release

#1319 Internal - Modify the Markdown Summary Artifactory links
  artifactory/utils/commandsummary/buildinfosummary.go
  artifactory/utils/commandsummary/buildinfosummary_test.go
  artifactory/utils/commandsummary/uploadsummary.go
  artifactory/utils/commandsummary/utils.go
  artifactory/utils/commandsummary/utils_test.go
  artifactory/utils/testdata/command_summaries/extended/build-info-table.md
  artifactory/utils/testdata/command_summaries/extended/docker-image-module.md
  artifactory/utils/testdata/command_summaries/extended/generic-module.md
  artifactory/utils/testdata/command_summaries/extended/maven-module.md
  artifactory/utils/testdata/command_summaries/extended/maven-nested-module.md
  artifactory/utils/testdata/command_summaries/extended/multiarch-docker-image.md
Labels: improvement

#1320 Internal - Set a min Artifactory version for Visibility System usage
  artifactory/commands/transferfiles/transfer.go
  artifactory/utils/utils.go
  common/commands/command.go
  go.mod
  go.sum
  utils/usage/usage.go
  utils/usage/visibility_system_manager.go
Labels: improvement

#1321 Upgrade jfrog-client-go
  go.mod
  go.sum
Labels: ignore for release

#1322 Fix visibility system calling
  utils/usage/visibility_system_manager.go
Labels: bug
