Repository jfrog/jfrog-cli-core, pull requests merged in 2024-02, with the labels that each got.

#1121 Artifactory Release Lifecycle Management - Modify release bundle promotion properties
  go.mod
  go.sum
  lifecycle/common.go
  lifecycle/createcommon.go
  lifecycle/createfrombuilds.go
  lifecycle/createfrombundles.go
  lifecycle/promote.go
Labels: breaking change, improvement

#1123 Artifactory Release Lifecycle Management - Add include dependencies option to release bundle creation
  go.mod
  go.sum
  lifecycle/createfrombuilds.go
Labels: new feature

#844 Artifactory Repository Templates - OptionalIndexCompressionFormats & PrimaryKeyPairRef properties added
  artifactory/commands/repository/repository.go
  artifactory/commands/repository/template.go
Labels: improvement

#1127 Use Go-Sec 2.18.0
  .github/workflows/analysis.yml
Labels: ignore for release

#1118 Maven support for curation audit cmd.
  tests/testdata/maven-example-with-many-types/pom.xml
  utils/java/deptreemanager.go
  utils/java/gradle.go
  utils/java/mvn.go
  utils/java/mvn_test.go
  utils/xray/xrayutils.go
Labels: improvement

#1126 Export "isProcessRunning"
  utils/lock/lock.go
  utils/osutils/utils_unix.go
  utils/osutils/utils_windows.go
Labels: improvement

#1122 Add Pnpm technology
  artifactory/commands/repository/template.go
  utils/coreutils/techutils.go
  utils/coreutils/techutils_test.go
Labels: improvement

#1110 Improve interactive build config creation repositories fetch efficiency
  artifactory/utils/repositoryutils.go
  common/commands/configfile.go
Labels: improvement

#1130 Fix panic in build-scan without arguments
  plugins/common/config.go
Labels: bug

#1111 Add Terraform/Cargo repository creation commands
  .github/workflows/test.yml
  artifactory/commands/repository/repository.go
  artifactory/commands/repository/template.go
  go.mod
  go.sum
Labels: improvement

#1132 Add Pnpm as project type for config
  common/project/projectconfig.go
Labels: improvement

#1128 Moved Golang remote registry setting logic from security-cli to cli-core
  artifactory/commands/golang/go.go
  artifactory/commands/golang/go_test.go
Labels: ignore for release

#1133 Update build-info-go and jfrog-client-go dependencies
  go.mod
  go.sum
Labels: ignore for release

#1134 Upgrade jfrog-cli-core to 2.48.1
  go.mod
  go.sum
Labels: ignore for release

#1125 Fix upload and download progress bars
  artifactory/commands/generic/upload.go
  artifactory/commands/transferfiles/state/timeestimation.go
  artifactory/commands/transferfiles/state/timeestimation_test.go
  artifactory/commands/transferfiles/state/utils.go
  artifactory/utils/storageinfo.go
  artifactory/utils/storageinfo_test.go
  artifactory/utils/upload.go
  common/progressbar/filesprogressbar.go
  common/progressbar/filesprogressbar_test.go
  common/progressbar/readerprogressbar.go
  common/progressbar/simpleprogressbar.go
  go.mod
  go.sum
  utils/progressbar/progressbarmng.go
Labels: bug

#1131 Update build info go dotnet
  artifactory/commands/dotnet/nuget.go
  go.mod
  go.sum
Labels: ignore for release

#1137 Fix interactive Maven config command
  common/commands/configfile.go
Labels: bug
