Repository jfrog/jfrog-cli-core, pull requests merged in 2024-11, with the labels that each got.

#1288 Cocoapods config for Artifactory repositories
  common/commands/configfile.go
  common/project/projectconfig.go
Labels: improvement

#1289 Remove remaining temp file after Artifactory download
  go.mod
  go.sum
Labels: bug

#1292 Make the CheckExtendedSummaryEntitled API public
  artifactory/utils/commandsummary/markdownConfig.go
Labels: improvement

#1293 Upgrade jfrog-client-go to v1.47.4
  go.mod
  go.sum
Labels: ignore for release

#1296 Prep code for a `jf audit` command for Swift
  common/commands/configfile.go
  common/project/projectconfig.go
Labels: ignore for release

#1298 Upgrade build-info-go & jfrog-client-go
  go.mod
  go.sum
Labels: ignore for release

#1300 Upgrade build-info-go & jfrog-client-go
  go.mod
  go.sum
Labels: improvement

#1299 Add commands to usage report
  artifactory/commands/buildinfo/publish.go
  common/commands/command.go
  common/commands/config.go
  common/commands/config_test.go
  utils/coreutils/coreconsts.go
Labels: improvement

#1301 Update dependencies
  go.mod
  go.sum
Labels: ignore for release

#1302 Nuget - Add `allowInsecureConnections` flag for package sources
  artifactory/commands/dotnet/dotnetcommand.go
  artifactory/commands/dotnet/dotnetcommand_test.go
  go.mod
  go.sum
Labels: improvement

#1305 FIx Nuget & DotNet tests
  artifactory/commands/dotnet/dotnetcommand.go
  artifactory/commands/dotnet/dotnetcommand_test.go
Labels: ignore for release

#1303 Create spec from variables
  common/spec/specfiles.go
  common/spec/specfiles_test.go
Labels: improvement

#1306 Upgrade build-info-go & jfrog-client-go
  go.mod
  go.sum
Labels: ignore for release
