Repository jfrog/jfrog-cli-core, pull requests merged in 2024-01, with the labels that each got.

#1096 Transfer - Use tmp dir under user home
  artifactory/commands/transferfiles/transfer.go
  artifactory/commands/transferfiles/utils.go
  artifactory/commands/transferfiles/utils_test.go
  utils/coreutils/coreconsts.go
  utils/coreutils/utils.go
Labels: bug

#1064 Enhanced CLI Plugins
  plugins/README.md
  plugins/commonutils.go
  plugins/components/commandcomp.go
  plugins/components/conversionlayer.go
  plugins/components/conversionlayer_test.go
  plugins/components/structure.go
  plugins/pluginmain.go
Labels: improvement

#1097 Bump maven-dep-tree to 1.1.0
  buildscripts/download-jars.sh
  xray/commands/audit/sca/java/mvn.go
  xray/commands/audit/sca/java/resources/maven-dep-tree.jar
Labels: improvement

#1098 Update dependencies
  go.mod
  go.sum
Labels: ignore for release

#1099 Fix negative table width on terminals such as CircleCI
  go.mod
  go.sum
  utils/coreutils/tableutils.go
Labels: bug

#1095 Move content from jfrog-cli repo to jfrog-cli-core
  common/cliutils/cli_consts.go
  common/cliutils/utils.go
  common/progressbar/filesprogressbar.go
  common/progressbar/filesprogressbar_test.go
  common/progressbar/readerprogressbar.go
  common/progressbar/simpleprogressbar.go
  common/tests/docker.go
  common/tests/utils.go
  plugins/common/config.go
  plugins/common/server.go
  plugins/common/utils.go
  plugins/commonutils.go
  plugins/components/conversionlayer.go
  utils/tests/test_cli.go
  utils/tests/test_utils.go
  utils/tests/utils.go
Labels: ignore for release

#1105 Improve recursive scan detection
  xray/commands/audit/audit.go
  xray/commands/audit/auditparams.go
  xray/commands/audit/scarunner.go
  xray/commands/audit/scarunner_test.go
Labels: improvement

#1109 Fix wrong duplication of repositories IncludeExclude Filter
  .github/workflows/analysis.yml
  artifactory/utils/repositoryutils.go
  go.mod
  go.sum
Labels: bug

#1112 Update utils_test.go
  utils/golang/utils_test.go
Labels: ignore for release

#1114 Upgrade to v2.47.11
  go.mod
  go.sum
Labels: ignore for release

#1108 NPM - Update NpmCommand class with an Artifactory configuration function
  artifactory/commands/npm/npmcommand.go
  artifactory/commands/npm/npmcommand_test.go
  tests/testdata/npm-project/helloworld.js
  tests/testdata/npm-project/package.json
Labels: ignore for release

#1115 Modifications to RunMavenDepTree and Maven dependency tree construction
  utils/java/deptreemanager.go
  utils/java/mvn.go
  utils/java/mvn_test.go
Labels: ignore for release

#1116 Optimization to clearMavenDepTreeRun call
  utils/java/mvn.go
Labels: ignore for release

#1117 Join error on GetRepoConfigByPrefix
  common/project/projectconfig.go
Labels: bug

#1119 Upgrade jfrog-cli-core to 2.47.12
  artifactory/commands/npm/npmcommand.go
  artifactory/commands/npm/npmcommand_test.go
  common/project/projectconfig.go
  tests/testdata/npm-project/helloworld.js
  tests/testdata/npm-project/package.json
  utils/java/deptreemanager.go
  utils/java/mvn.go
  utils/java/mvn_test.go
Labels: ignore for release
