Repository jfrog/jfrog-cli-core, pull requests merged in 2024-08, with the labels that each got.

#1220 Move crypto/checksum code to gofrog
  artifactory/commands/generic/props.go
  artifactory/commands/generic/setprops.go
  artifactory/commands/golang/archive_test.go
  artifactory/commands/golang/publish.go
  artifactory/commands/transferfiles/state/utils.go
  artifactory/utils/search.go
  go.mod
  go.sum
Labels: ignore for release

#1221 Improve artifacts links in command summaries
  artifactory/commands/buildinfo/publish.go
  artifactory/commands/commandssummaries/buildinfosummary.go
  artifactory/commands/commandssummaries/buildinfosummary_test.go
  artifactory/commands/commandssummaries/testdata/modules.md
  artifactory/commands/commandssummaries/uploadsummary.go
  artifactory/commands/commandssummaries/utils.go
  artifactory/commands/commandssummaries/utils_test.go
  artifactory/commands/generic/upload.go
Labels: improvement

#1219 Skip modules without artifacts in command summary
  artifactory/commands/commandssummaries/buildinfosummary.go
  artifactory/commands/commandssummaries/buildinfosummary_test.go
Labels: improvement

#1222 Upgrade jfrog-cli-core to 2.54.1
  go.mod
  go.sum
Labels: ignore for release

#1224 Update dependencies
  go.mod
  go.sum
  utils/usage/usage.go
Labels: ignore for release

#1226 Mvn - avoid parsing build info when it has not been collected
  artifactory/commands/mvn/mvn.go
Labels: bug

#1228 Add Metadata service support
  artifactory/utils/utils.go
  go.mod
  go.sum
  utils/config/config.go
Labels: new feature

#1233 Promote to v2.54.3
  artifactory/commands/npm/publish.go
  go.mod
  go.sum
  utils/config/config.go
Labels: ignore for release

#1234 Promote to 2.55.1
  go.mod
  go.sum
Labels: ignore for release

#1229 Job Summary - Group Build-Info Related Modules into the Same Section
  artifactory/commands/commandssummaries/buildinfosummary.go
  artifactory/commands/commandssummaries/buildinfosummary_test.go
  artifactory/commands/commandssummaries/testdata/generic.md
  artifactory/commands/commandssummaries/testdata/image2.md
  artifactory/commands/commandssummaries/testdata/maven.md
  artifactory/commands/commandssummaries/testdata/modules.md
  artifactory/commands/commandssummaries/testdata/multiarch-image1.md
  artifactory/utils/container/buildinfo.go
Labels: improvement

#1236 Job Summary - Handle Docker Multi-Module Sections Separately
  artifactory/commands/commandssummaries/buildinfosummary.go
  artifactory/commands/commandssummaries/buildinfosummary_test.go
  artifactory/commands/commandssummaries/testdata/multiarch-image1.md
  artifactory/commands/commandssummaries/utils.go
  artifactory/utils/container/buildinfo.go
Labels: improvement

#1225 Recognize "403 forbidden" error from pip command output, and clasiffy it as "forbidden" error type
  artifactory/commands/python/python.go
  go.mod
  go.sum
Labels: improvement

#1237 Promote to v2.55.2
  go.mod
  go.sum
Labels: ignore for release

#1230 Command Summary - New record functionality
  artifactory/commands/buildinfo/publish.go
  artifactory/commands/commandssummaries/utils.go
  artifactory/commands/commandssummaries/utils_test.go
  artifactory/commands/generic/upload.go
  artifactory/utils/commandsummary/buildinfosummary.go
  artifactory/utils/commandsummary/buildinfosummary_test.go
  artifactory/utils/commandsummary/commandsummary.go
  artifactory/utils/commandsummary/commandsummary_test.go
  artifactory/utils/commandsummary/uploadsummary.go
  artifactory/utils/commandsummary/utils.go
  artifactory/utils/commandsummary/utils_test.go
  artifactory/utils/testdata/command_summaries/generic.md
  artifactory/utils/testdata/command_summaries/image2.md
  artifactory/utils/testdata/command_summaries/maven.md
  artifactory/utils/testdata/command_summaries/modules.md
  artifactory/utils/testdata/command_summaries/multiarch-image1.md
  artifactory/utils/testdata/command_summaries/table.md
  commandsummary/commandsummary.go
  commandsummary/commandsummary_test.go
Labels: improvement

#1239 Rename the JFROG_CLI_TRANSITIVE_DOWNLOAD_EXPERIMENTAL environment variable
  utils/coreutils/coreconsts.go
Labels: improvement

#1241 Rename the JFROG_CLI_TRANSITIVE_DOWNLOAD_EXPERIMENTAL environment variable
  utils/coreutils/coreconsts.go
Labels: improvement

#1242 Files progressbar - clean headline when setting a new message
  common/progressbar/filesprogressbar.go
Labels: improvement

#1244 Files Progress Bar - remove unnecessary nil assignment
  common/progressbar/filesprogressbar.go
Labels: ignore for release

#1247 Promote to v2.55.4
  common/progressbar/filesprogressbar.go
  go.mod
  go.sum
Labels: ignore for release

#1248 Promote to v2.55.4
  go.mod
  go.sum
Labels: ignore for release

#1243 Add missing priorityResolution and cdnRedirect to repository template creation
  artifactory/commands/repository/repository.go
  artifactory/commands/repository/template.go
  artifactory/commands/transferfiles/localgeneratedfilter.go
  artifactory/commands/transferfiles/srcpluginservice.go
  go.mod
  go.sum
Labels: improvement

#1251 Upgrade jfrog-cli-core to 2.55.5
  go.mod
  go.sum
Labels: ignore for release

#1249 Implement ClearProgress() for filesProgressBar
  common/progressbar/filesprogressbar.go
  go.mod
  go.sum
Labels: improvement

#1252 Wrap CleanOldDir warning with informative message
  plugins/pluginmain.go
Labels: improvement

#1245 Command Summary - New UI
  artifactory/utils/commandsummary/buildinfosummary.go
  artifactory/utils/commandsummary/buildinfosummary_test.go
  artifactory/utils/commandsummary/commandsummary.go
  artifactory/utils/commandsummary/commandsummary_test.go
  artifactory/utils/commandsummary/markdownConfig.go
  artifactory/utils/commandsummary/uploadsummary.go
  artifactory/utils/commandsummary/utils.go
  artifactory/utils/commandsummary/utils_test.go
  artifactory/utils/filetree.go
  artifactory/utils/filetree_test.go
  artifactory/utils/testdata/command_summaries/basic/build-info-table.md
  artifactory/utils/testdata/command_summaries/basic/docker-image-module.md
  artifactory/utils/testdata/command_summaries/basic/generic-module.md
  artifactory/utils/testdata/command_summaries/basic/maven-module.md
  artifactory/utils/testdata/command_summaries/basic/multiarch-docker-image.md
  artifactory/utils/testdata/command_summaries/extended/build-info-table.md
  artifactory/utils/testdata/command_summaries/extended/docker-image-module.md
  artifactory/utils/testdata/command_summaries/extended/generic-module.md
  artifactory/utils/testdata/command_summaries/extended/maven-module.md
  artifactory/utils/testdata/command_summaries/extended/multiarch-docker-image.md
Labels: improvement

#1253 Upgrade jfrog-cli-core to 2.55.6
  go.mod
  go.sum
Labels: ignore for release

#1255 Allow building JFrog CLI from sources on OpenBSD
  go.mod
  utils/coreutils/coreconsts.go
  utils/osutils/utils_unix.go
Labels: improvement
