Repository jfrog/jfrog-cli-core, pull requests merged in 2024-09, with the labels that each got.

#1256 Update Summaries extended page link & Add logs
  artifactory/utils/commandsummary/buildinfosummary.go
  artifactory/utils/commandsummary/commandsummary.go
  artifactory/utils/commandsummary/markdownConfig.go
  artifactory/utils/testdata/command_summaries/basic/build-info-table.md
  artifactory/utils/testdata/command_summaries/basic/docker-image-module.md
  artifactory/utils/testdata/command_summaries/basic/generic-module.md
  artifactory/utils/testdata/command_summaries/basic/maven-module.md
  artifactory/utils/testdata/command_summaries/basic/multiarch-docker-image.md
Labels: ignore for release

#1257 Command Summary - Separate Module Table View from Artifacts Tree
  artifactory/utils/commandsummary/buildinfosummary.go
  artifactory/utils/commandsummary/buildinfosummary_test.go
  artifactory/utils/commandsummary/commandsummary.go
  artifactory/utils/testdata/command_summaries/basic/generic-module.md
  artifactory/utils/testdata/command_summaries/basic/maven-module.md
  artifactory/utils/testdata/command_summaries/basic/maven-nested-module.md
  artifactory/utils/testdata/command_summaries/extended/generic-module.md
  artifactory/utils/testdata/command_summaries/extended/maven-module.md
  artifactory/utils/testdata/command_summaries/extended/maven-nested-module.md
Labels: improvement

#1260 Make command summary util available
  artifactory/utils/commandsummary/commandsummary.go
  artifactory/utils/commandsummary/commandsummary_test.go
Labels: ignore for release

#1262 Update dependencies
  artifactory/commands/transferfiles/fulltransfer.go
  artifactory/commands/transferfiles/longpropertycheck_test.go
  artifactory/commands/transferfiles/manager.go
  artifactory/commands/transferfiles/state/statemanager.go
  artifactory/commands/transferfiles/state/statemanager_test.go
  artifactory/commands/transferfiles/state/timeestimation.go
  artifactory/commands/transferfiles/state/timeestimation_test.go
  artifactory/commands/transferfiles/status.go
  artifactory/commands/transferfiles/transfer.go
  artifactory/commands/utils/precheckrunner/checkrunner.go
  artifactory/commands/utils/precheckrunner/checkrunner_test.go
  artifactory/commands/utils/precheckrunner/remoteurlchecker.go
  go.mod
  go.sum
  utils/config/encryption.go
  utils/coreutils/profiler.go
  utils/progressbar/transferprogressbarmanager.go
  utils/reposnapshot/snapshotmanager_test.go
Labels: ignore for release

#1258 Remove self-signed certificate question in Config
  common/commands/config.go
Labels: improvement

#1263 Start Progress Bar with 1 Filler (🟦) to avoid initial empty display
  go.mod
  go.sum
  utils/progressbar/progressbarmng.go
Labels: improvement

#1266 Add uploadServiceOptions to UploadFiles service
  artifactory/commands/generic/upload.go
  artifactory/commands/npm/publish.go
  artifactory/commands/terraform/terraformpublish.go
  go.mod
  go.sum
Labels: ignore for release

#1267 Add twine support
  artifactory/commands/python/twine.go
  artifactory/utils/commandsummary/buildinfosummary.go
  common/commands/configfile.go
  go.mod
  go.sum
  utils/coreutils/cmdutils.go
Labels: new feature

#1268 Promote to v2.56.0
  go.mod
  go.sum
Labels: ignore for release

#1270 Fix path to build info JARs documentation
  utils/dependencies/utils.go
Labels: ignore for release

#1271 Promote to v2.56.1
  go.mod
  go.sum
Labels: ignore for release

#1276 Upgrade build-info-go to v1.10.2
  go.mod
  go.sum
Labels: improvement
