Repository jfrog/jfrog-cli-core, pull requests merged in 2024-04, with the labels that each got.

#1165 New XSC analytics metrics capabilities
  go.mod
  go.sum
  utils/config/config.go
Labels: improvement

#1167 Duplicate App Name at plugins help usage
  plugins/components/conversionlayer.go
  plugins/components/conversionlayer_test.go
Labels: bug

#1155 Support pip for curation
  artifactory/commands/python/poetry.go
  artifactory/commands/python/python.go
  utils/coreutils/coreconsts.go
  utils/python/utils.go
  utils/python/utils_test.go
Labels: improvement

#1171 Fix npm pack command with prePack script
  artifactory/utils/npm/pack.go
  tests/testdata/npm-workspaces/package.json
Labels: bug

#1172 Promote v2.51.0
  go.mod
  go.sum
Labels: ignore for release

#1169 Support providing chunk size in multi part upload
  artifactory/commands/generic/upload.go
  artifactory/commands/transferfiles/utils.go
  artifactory/utils/storageinfo.go
  artifactory/utils/storageinfo_test.go
  artifactory/utils/upload.go
  go.mod
  go.sum
  utils/progressbar/progressbarmng.go
Labels: improvement

#1146 Add OCI technology
  utils/coreutils/techutils.go
Labels: improvement
