Repository jfrog/jfrog-cli-core, pull requests merged in 2025-07, with the labels that each got.

#1403 Add Cyclonedx Output format
  common/format/output.go
Labels: improvement

#1416 Method-to-read-repo-template-configs
  artifactory/commands/utils/templateutils.go
  go.mod
  go.sum
Labels: ignore for release, safe-to-test

#1421 Added ValidateRepoType method in utils.
  artifactory/utils/utils.go
Labels: ignore for release
