Repository jfrog/jfrog-cli-core, pull requests merged in 2025-05, with the labels that each got.

#1378 Fix `jf eot` response to a valid json
  general/token/oidctokenexchange.go
Labels: bug

#1384 Introduced support for lifecycle annotate command
  go.mod
  go.sum
Labels: new feature

#1387 Update Dependencies
  go.mod
  go.sum
Labels: ignore for release

#1391 Update Dependencies
  go.mod
  go.sum
Labels: ignore for release
