Repository jfrog/jfrog-cli-core, pull requests merged in 2025-01, with the labels that each got.

#1324 Test Cli outputs of cmd with errors
  utils/tests/test_cli.go
Labels: ignore for release

#1325 Command Summary - Add visibility system query params
  artifactory/utils/commandsummary/utils.go
  artifactory/utils/commandsummary/utils_test.go
  artifactory/utils/testdata/command_summaries/extended/build-info-table.md
  artifactory/utils/testdata/command_summaries/extended/docker-image-module.md
  artifactory/utils/testdata/command_summaries/extended/generic-module.md
  artifactory/utils/testdata/command_summaries/extended/maven-module.md
  artifactory/utils/testdata/command_summaries/extended/maven-nested-module.md
  artifactory/utils/testdata/command_summaries/extended/multiarch-docker-image.md
  utils/usage/visibility_system_manager.go
Labels: improvement

#1329 Avoid suggesting go Remote repositories as potential resolver repository in go-config
  common/commands/configfile.go
Labels: improvement

#1331 Added support for printing red & green colored text
  utils/coreutils/cmdutils.go
Labels: improvement

#1336 Create temp dir if doesnt exist
  go.mod
  go.sum
  utils/coreutils/utils.go
Labels: bug

#1330 Visibility - update commands count metric to correspond with client changes
  common/commands/command.go
  go.mod
  go.sum
  utils/usage/visibility/commands_count_metric.go
  utils/usage/visibility/commands_count_metric_test.go
  utils/usage/visibility/visibility_system_manager.go
  utils/usage/visibility_system_manager.go
Labels: ignore for release

#1338 Update Dependencies
  go.mod
  go.sum
Labels: ignore for release

#1341 Downgrade Go version
  go.mod
Labels: ignore for release
