Repository jfrog/jfrog-cli-core, pull requests merged in 2025-06, with the labels that each got.

#1399 One model support
  artifactory/utils/utils.go
  go.mod
  go.sum
  utils/config/config.go
Labels: new feature, safe-to-test

#1405 fix slash issue in build name, number in rbc
  common/spec/specfiles.go
  common/spec/specfiles_test.go
Labels: bug

#1411 Add OIDC context struct
  common/commands/config.go
  general/token/oidctokenexchange.go
  go.mod
  go.sum
  utils/coreutils/coreconsts.go
Labels: improvement
